import test from 'node:test';
import assert from 'node:assert/strict';
import { rm, writeFile, mkdir, readFile, readdir } from 'node:fs/promises';
import path from 'node:path';
import { initGit, runEngram, tempWorkspace, workspaceMemoryRoot } from '../helpers.mjs';
import { machineProfileName, packageVersion, testMemory } from './fixtures.mjs';

test('upgrade plan reports quick package update and registered global skillset refresh', async () => {
  const { cwd, env } = await tempWorkspace('engram-cli-upgrade-');
  const agentHome = path.join(cwd, 'agent-home');
  const globalEnv = { ...env, ENGRAM_AGENT_HOME: agentHome, ENGRAM_AGENT_CONFIG_HOME: path.join(cwd, 'agent-config') };
  const installed = await runEngram(cwd, globalEnv, ['link', '--global', 'codex']);
  assert.equal(installed.code, 0, installed.stderr);
  await writeFile(path.join(cwd, 'AGENTS.md'), '<!-- Generated by Engram skillset installer. Edit with care. -->\n# Old Engram instructions\n');

  const plan = await runEngram(cwd, globalEnv, ['upgrade', '--plan', '--no-version-check']);
  assert.equal(plan.code, 0, plan.stderr);
  assert.match(plan.stdout, /Upgrade plan/);
  assert.match(plan.stdout, /PACKAGE recommendation/);
  assert.match(plan.stdout, /PLAN workspace skillsets/);
  assert.match(plan.stdout, /PLANNED agents-md: AGENTS\.md/);
  assert.match(plan.stdout, /PLAN global memory/);
  assert.match(plan.stdout, /PLANNED codex: .*AGENTS\.md/);
  assert.match(plan.stdout, /Quick update:/);
  assert.match(plan.stdout, /npm install -g @the-long-ride\/engram@latest/);
  assert.match(await readFile(path.join(cwd, 'AGENTS.md'), 'utf8'), /Old Engram instructions/);
  await rm(cwd, { recursive: true, force: true });
});

test('upgrade refreshes generated workspace skillsets', async () => {
  const { cwd, env } = await tempWorkspace('engram-cli-upgrade-skillset-');
  const init = await runEngram(cwd, env, ['inject', '--no-skillset']);
  assert.equal(init.code, 0, init.stderr);
  await writeFile(path.join(cwd, 'AGENTS.md'), '<!-- Generated by Engram skillset installer. Edit with care. -->\n# Old Engram instructions\n');
  await mkdir(path.join(cwd, '.agents', 'skills', 'engram'), { recursive: true });
  await writeFile(path.join(cwd, '.agents', 'skills', 'engram', 'SKILL.md'), [
    '---',
    'name: engram',
    'description: old',
    '---',
    '# Engram Memory Skill',
    ''
  ].join('\n'));

  const upgraded = await runEngram(cwd, env, ['upgrade', '--no-version-check']);
  assert.equal(upgraded.code, 0, upgraded.stderr);
  assert.match(upgraded.stdout, /UPDATED workspace skillsets/);
  assert.match(upgraded.stdout, /UPDATED agents-md: AGENTS\.md/);
  assert.match(upgraded.stdout, /UPDATED agent-skill: \.agents\/skills\/engram\/SKILL\.md/);
  const agentsMd = await readFile(path.join(cwd, 'AGENTS.md'), 'utf8');
  assert.match(agentsMd, /<!-- engram:start -->/);
  assert.match(agentsMd, /Full guide:/);
  assert.match(await readFile(path.join(cwd, '.agents', 'skills', 'engram', 'SKILL.md'), 'utf8'), /Engram Memory Management Skill/);
  await rm(cwd, { recursive: true, force: true });
});

test('upgrade creates a machine default profile for legacy global-only installs', async () => {
  const { cwd, env } = await tempWorkspace('engram-cli-upgrade-profile-');
  const customEnv = { ...env };
  delete customEnv.ENGRAM_GLOBAL_DIR;
  const globalPath = path.join(cwd, 'portable-engram');
  const init = await runEngram(cwd, customEnv, ['inject', '--global-only', '--global-path', globalPath]);
  assert.equal(init.code, 0, init.stderr);
  await rm(path.join(customEnv.ENGRAM_CONFIG_DIR, 'profiles.json'), { force: true });
  const globalConfigFile = path.join(globalPath, 'engram.config.json');
  const globalConfig = JSON.parse(await readFile(globalConfigFile, 'utf8'));
  globalConfig.version = '0.0.0';
  globalConfig.auto_upgrade = { version: '0.0.0', checked_at: '2026-01-01T00:00:00.000Z' };
  await writeFile(globalConfigFile, `${JSON.stringify(globalConfig, null, 2)}\n`);

  const upgraded = await runEngram(cwd, customEnv, ['upgrade', '--no-version-check']);
  assert.equal(upgraded.code, 0, upgraded.stderr);
  assert.match(upgraded.stdout, /default profile created/);
  const profiles = JSON.parse(await readFile(path.join(customEnv.ENGRAM_CONFIG_DIR, 'profiles.json'), 'utf8'));
  const expected = machineProfileName();
  assert.equal(profiles.active_profile, expected);
  assert.equal(profiles.profiles[expected].global_path, globalPath);
  const entry = await runEngram(cwd, customEnv, ['entry']);
  assert.equal(entry.code, 0, entry.stderr);
  assert.match(entry.stdout.replace(/\x1b\[[0-9;]*m/g, ''), new RegExp(`profile\\.active:\\s*${expected.replace(/[\\^$.*+?()[\]{}|]/g, '\\$&')}`));
  await rm(cwd, { recursive: true, force: true });
});

test('auto-upgrade quietly reconciles initialized roots once after package updates', async () => {
  const { cwd, env } = await tempWorkspace('engram-cli-autoupgrade-');
  const init = await runEngram(cwd, env, ['inject']);
  assert.equal(init.code, 0, init.stderr);
  const root = workspaceMemoryRoot(cwd);
  const configFile = path.join(root, 'engram.config.json');
  const config = JSON.parse(await readFile(configFile, 'utf8'));
  config.version = '0.0.0';
  config.auto_upgrade = { version: '0.0.0', checked_at: '2026-01-01T00:00:00.000Z' };
  await writeFile(configFile, `${JSON.stringify(config, null, 2)}\n`);
  await rm(path.join(root, 'HELP.md'), { force: true });
  await writeFile(path.join(cwd, 'AGENTS.md'), '<!-- Generated by Engram skillset installer. Edit with care. -->\n# Old Engram instructions\n');

  const loaded = await runEngram(cwd, env, ['load', '--dry-run', 'auto upgrade probe']);
  assert.equal(loaded.code, 0, loaded.stderr);
  assert.doesNotMatch(loaded.stdout, /auto-upgrade|reconciled/i);
  assert.match(await readFile(path.join(root, 'HELP.md'), 'utf8'), /Engram Help/);
  const autoAgentsMd = await readFile(path.join(cwd, 'AGENTS.md'), 'utf8');
  assert.match(autoAgentsMd, /<!-- engram:start -->/);
  assert.match(autoAgentsMd, /Full guide:/);
  const upgradedConfig = JSON.parse(await readFile(configFile, 'utf8'));
  assert.equal(upgradedConfig.version, await packageVersion());
  assert.equal(upgradedConfig.auto_upgrade.version, await packageVersion());

  const beforeSecondRun = await readFile(configFile, 'utf8');
  const second = await runEngram(cwd, env, ['search', 'auto upgrade probe']);
  assert.equal(second.code, 0, second.stderr);
  assert.equal(await readFile(configFile, 'utf8'), beforeSecondRun);
  await rm(cwd, { recursive: true, force: true });
});

test('auto-upgrade reconciles v0.0.8 roots through current routing metadata', async () => {
  const { cwd, env } = await tempWorkspace('engram-cli-autoupgrade-index-');
  const init = await runEngram(cwd, env, ['inject', '--no-skillset']);
  assert.equal(init.code, 0, init.stderr);
  const root = workspaceMemoryRoot(cwd);
  const configFile = path.join(root, 'engram.config.json');
  const config = JSON.parse(await readFile(configFile, 'utf8'));
  config.version = '0.0.8';
  config.auto_upgrade = { version: '0.0.8', checked_at: '2026-01-01T00:00:00.000Z' };
  config.graph = { ...config.graph, enabled: false };
  config.vector = { ...config.vector, enabled: false };
  delete config.proof;
  delete config.load;
  await writeFile(configFile, `${JSON.stringify(config, null, 2)}\n`);
  const dir = path.join(root, 'knowledge');
  await mkdir(dir, { recursive: true });
  const filler = Array.from({ length: 80 }, (_, index) => `ordinary-${index}`).join(' ');
  await writeFile(path.join(dir, 'late-upgrade-keyword.md'), testMemory({
    id: 'late-upgrade-keyword',
    tags: ['routing'],
    content: `${filler} upgrade-routing-token appears after the compact summary cutoff.`
  }));
  const rebuilt = await runEngram(cwd, env, ['rebuild-index', 'workspace', '--no-auto-upgrade']);
  assert.equal(rebuilt.code, 0, rebuilt.stderr);
  const indexFile = path.join(root, 'memory.index.json');
  const oldIndex = JSON.parse(await readFile(indexFile, 'utf8'));
  oldIndex.version = '0.0.8';
  oldIndex.entries = oldIndex.entries.map((entry) => {
    const { routingTerms, ...rest } = entry;
    return rest;
  });
  await writeFile(indexFile, `${JSON.stringify(oldIndex, null, 2)}\n`);

  const loaded = await runEngram(cwd, env, ['load', '--dry-run', 'upgrade-routing-token']);

  assert.equal(loaded.code, 0, loaded.stderr);
  assert.match(loaded.stdout, /late-upgrade-keyword/);
  const upgradedIndex = JSON.parse(await readFile(indexFile, 'utf8'));
  assert.ok(upgradedIndex.entries.every((entry) => Array.isArray(entry.routingTerms)));
  const upgradedConfig = JSON.parse(await readFile(configFile, 'utf8'));
  assert.equal(upgradedConfig.version, await packageVersion());
  assert.equal(upgradedConfig.auto_upgrade.version, await packageVersion());
  assert.equal(upgradedConfig.proof, 'off');
  assert.equal(upgradedConfig.load.limit, 8);
  await rm(cwd, { recursive: true, force: true });
});

test('auto-upgrade creates a machine default profile for legacy global installs', async () => {
  const { cwd, env } = await tempWorkspace('engram-cli-autoprofile-');
  const init = await runEngram(cwd, env, ['inject', '--no-skillset', '--scope', 'global']);
  assert.equal(init.code, 0, init.stderr);
  await rm(path.join(env.ENGRAM_CONFIG_DIR, 'profiles.json'), { force: true });
  const root = workspaceMemoryRoot(cwd);
  const configFile = path.join(root, 'engram.config.json');
  const config = JSON.parse(await readFile(configFile, 'utf8'));
  config.version = '0.0.0';
  config.auto_upgrade = { version: '0.0.0', checked_at: '2026-01-01T00:00:00.000Z' };
  config.scope = 'global';
  config.global_git.branch = 'legacy-default';
  await writeFile(configFile, `${JSON.stringify(config, null, 2)}\n`);

  const loaded = await runEngram(cwd, env, ['load', '--dry-run', 'legacy default profile']);
  assert.equal(loaded.code, 0, loaded.stderr);
  const profiles = JSON.parse(await readFile(path.join(env.ENGRAM_CONFIG_DIR, 'profiles.json'), 'utf8'));
  const expected = machineProfileName();
  assert.equal(profiles.active_profile, expected);
  assert.equal(profiles.profiles[expected].global_path, env.ENGRAM_GLOBAL_DIR);
  assert.equal(profiles.profiles[expected].scope, 'global');
  assert.equal(profiles.profiles[expected].global_git.branch, 'legacy-default');

  const noEnv = { ...env };
  delete noEnv.ENGRAM_GLOBAL_DIR;
  const entry = await runEngram(cwd, noEnv, ['entry']);
  assert.equal(entry.code, 0, entry.stderr);
  const clean = entry.stdout.replace(/\x1b\[[0-9;]*m/g, '');
  assert.match(clean, new RegExp(`profile\\.active:\\s*${expected.replace(/[\\^$.*+?()[\]{}|]/g, '\\$&')}`));
  assert.match(clean, new RegExp(`roots\\.global:\\s*${env.ENGRAM_GLOBAL_DIR.replace(/[\\^$.*+?()[\]{}|]/g, '\\$&')}`));
  await rm(cwd, { recursive: true, force: true });
});

test('upgrade refresh keeps codex-linked AGENTS.md as bootstrap', async () => {
  const { cwd, env } = await tempWorkspace('engram-cli-upgrade-codex-');
  const link = await runEngram(cwd, env, ['link', 'codex']);
  assert.equal(link.code, 0, link.stderr);
  // Simulate stale bootstrap content (old version)
  await writeFile(path.join(cwd, 'AGENTS.md'), '<!-- Generated by Engram skillset installer. Edit with care. -->\n\n# Engram Agent Skillset\n\n## Runtime Bootstrap\n\n- Old bootstrap line.\n');

  const upgraded = await runEngram(cwd, env, ['upgrade', '--no-version-check']);
  assert.equal(upgraded.code, 0, upgraded.stderr);
  const agentsMd = await readFile(path.join(cwd, 'AGENTS.md'), 'utf8');
  assert.match(agentsMd, /<!-- engram:start -->/);
  assert.match(agentsMd, /Full guide:/);
  assert.doesNotMatch(agentsMd, /Save flow:/);
  await rm(cwd, { recursive: true, force: true });
});

test('upgrade --latest overwrites linked workspace cursor files and hooks', async () => {
  const { cwd, env } = await tempWorkspace('engram-cli-upgrade-latest-workspace-');
  const linked = await runEngram(cwd, env, ['link', 'cursor']);
  assert.equal(linked.code, 0, linked.stderr);

  const cursorDir = path.join(cwd, '.cursor');
  await writeFile(path.join(cursorDir, 'rules', 'engram.mdc'), '---\ndescription: stale\nalwaysApply: false\n---\n\n# stale rule\n');
  await writeFile(path.join(cursorDir, 'mcp.json'), `${JSON.stringify({ mcpServers: { engram: { type: 'stdio', command: 'old-bin', args: ['old'] } } }, null, 2)}\n`);
  await writeFile(path.join(cursorDir, 'hooks.json'), `${JSON.stringify({
    sessionStart: [{ name: 'engram-auto-load', type: 'command', command: 'echo stale', timeout: 1 }],
    custom: [{ name: 'keep-me', type: 'command', command: 'echo keep' }]
  }, null, 2)}\n`);

  const upgraded = await runEngram(cwd, env, ['upgrade', '--latest', '--no-version-check']);
  assert.equal(upgraded.code, 0, upgraded.stderr);
  assert.match(upgraded.stdout, /UPDATED workspace skillsets/);
  assert.match(upgraded.stdout, /UPDATED workspace agent hooks/);

  const rule = await readFile(path.join(cursorDir, 'rules', 'engram.mdc'), 'utf8');
  assert.match(rule, /alwaysApply:\s*true/);
  assert.match(rule, /<!-- engram:start -->/);

  const mcp = JSON.parse(await readFile(path.join(cursorDir, 'mcp.json'), 'utf8'));
  assert.equal(mcp.mcpServers.engram.command, 'npx');

  const hooks = JSON.parse(await readFile(path.join(cursorDir, 'hooks.json'), 'utf8'));
  const managed = hooks.sessionStart.find((entry) => entry.name === 'engram-auto-load');
  assert.ok(managed, 'cursor sessionStart should keep the managed engram hook');
  assert.equal(managed.command, 'engram agent-hook --host cursor');
  assert.equal(managed.timeout, 10000);
  assert.ok(hooks.custom.some((entry) => entry.name === 'keep-me'));

  await rm(cwd, { recursive: true, force: true });
});

test('upgrade --latest overwrites registered global cursor files and hooks', async () => {
  const { cwd, env } = await tempWorkspace('engram-cli-upgrade-latest-global-');
  const agentHome = path.join(cwd, 'agent-home');
  const globalEnv = { ...env, ENGRAM_AGENT_HOME: agentHome, ENGRAM_AGENT_CONFIG_HOME: path.join(cwd, 'agent-config') };
  const linked = await runEngram(cwd, globalEnv, ['link', '--global', 'cursor']);
  assert.equal(linked.code, 0, linked.stderr);

  const pluginRoot = path.join(agentHome, '.cursor', 'plugins', 'local', 'engram');
  await writeFile(path.join(pluginRoot, 'rules', 'engram.mdc'), '---\ndescription: stale\nalwaysApply: false\n---\n\n# stale rule\n');
  await writeFile(path.join(pluginRoot, 'mcp.json'), `${JSON.stringify({ mcpServers: { engram: { type: 'stdio', command: 'old-bin', args: ['old'] } } }, null, 2)}\n`);
  await writeFile(path.join(pluginRoot, 'hooks', 'hooks.json'), `${JSON.stringify({
    sessionStart: [{ name: 'engram-auto-load', type: 'command', command: 'echo stale', timeout: 1 }],
    custom: [{ name: 'keep-me', type: 'command', command: 'echo keep' }]
  }, null, 2)}\n`);
  await writeFile(path.join(pluginRoot, '.cursor-plugin', 'plugin.json'), `${JSON.stringify({ name: 'engram', version: '0.0.0', _managedBy: 'engram' }, null, 2)}\n`);

  const upgraded = await runEngram(cwd, globalEnv, ['upgrade', '--latest', '--no-version-check']);
  assert.equal(upgraded.code, 0, upgraded.stderr);
  assert.match(upgraded.stdout, /UPDATED global agent hooks/);

  const rule = await readFile(path.join(pluginRoot, 'rules', 'engram.mdc'), 'utf8');
  assert.match(rule, /alwaysApply:\s*true/);
  assert.match(rule, /<!-- engram:start -->/);

  const pluginJson = JSON.parse(await readFile(path.join(pluginRoot, '.cursor-plugin', 'plugin.json'), 'utf8'));
  assert.equal(pluginJson.name, 'engram');
  assert.equal(pluginJson._managedBy, 'engram');
  assert.equal(pluginJson.author, 'The Long Ride');

  const mcp = JSON.parse(await readFile(path.join(pluginRoot, 'mcp.json'), 'utf8'));
  assert.equal(mcp.mcpServers.engram.command, 'npx');

  const hooks = JSON.parse(await readFile(path.join(pluginRoot, 'hooks', 'hooks.json'), 'utf8'));
  const managed = hooks.sessionStart.find((entry) => entry.name === 'engram-auto-load');
  assert.ok(managed, 'global cursor hooks should keep the managed engram hook');
  assert.equal(managed.command, 'engram agent-hook --host cursor');
  assert.equal(managed.timeout, 10000);

  await rm(cwd, { recursive: true, force: true });
});
test('upgrade --latest replaces stale linked workspace claude hooks without duplicates', async () => {
  const { cwd, env } = await tempWorkspace('engram-cli-upgrade-latest-claude-hooks-');
  const linked = await runEngram(cwd, env, ['link', 'claude']);
  assert.equal(linked.code, 0, linked.stderr);

  const claudeDir = path.join(cwd, '.claude');
  await writeFile(path.join(claudeDir, 'settings.json'), `${JSON.stringify({
    hooks: {
      SessionStart: [{
        matcher: '*',
        hooks: [
          { name: 'engram-auto-load', type: 'command', command: 'echo stale', timeout: 1 },
          { name: 'keep-me', type: 'command', command: 'echo keep', timeout: 2 }
        ]
      }]
    }
  }, null, 2)}\n`);

  const upgraded = await runEngram(cwd, env, ['upgrade', '--latest', '--no-version-check']);
  assert.equal(upgraded.code, 0, upgraded.stderr);
  assert.match(upgraded.stdout, /UPDATED workspace agent hooks/);

  const settings = JSON.parse(await readFile(path.join(claudeDir, 'settings.json'), 'utf8'));
  const groups = settings.hooks.SessionStart;
  const managed = groups.flatMap((group) => group.hooks).filter((entry) => entry.name === 'engram-auto-load');
  assert.equal(managed.length, 1, 'claude SessionStart should keep exactly one managed engram hook');
  assert.equal(managed[0].command, 'engram agent-hook --host claude');
  assert.equal(managed[0].timeout, 10000);
  assert.ok(groups.some((group) => group.hooks.some((entry) => entry.name === 'keep-me')));

  await rm(cwd, { recursive: true, force: true });
});

test('upgrade --latest refreshes standalone workspace claude hooks without linked skillset', async () => {
  const { cwd, env } = await tempWorkspace('engram-cli-upgrade-latest-standalone-hooks-');
  const claudeDir = path.join(cwd, '.claude');
  await mkdir(claudeDir, { recursive: true });
  await writeFile(path.join(claudeDir, 'settings.json'), `${JSON.stringify({
    hooks: {
      SessionStart: [{
        matcher: '*',
        hooks: [
          { name: 'engram-auto-load', type: 'command', command: 'echo stale', timeout: 1 },
          { name: 'keep-me', type: 'command', command: 'echo keep', timeout: 2 }
        ]
      }]
    }
  }, null, 2)}\n`);

  const upgraded = await runEngram(cwd, env, ['upgrade', '--latest', '--no-version-check']);
  assert.equal(upgraded.code, 0, upgraded.stderr);
  assert.match(upgraded.stdout, /UPDATED workspace agent hooks/);

  const settings = JSON.parse(await readFile(path.join(claudeDir, 'settings.json'), 'utf8'));
  const managed = settings.hooks.SessionStart.flatMap((group) => group.hooks).filter((entry) => entry.name === 'engram-auto-load');
  assert.equal(managed.length, 1, 'standalone claude hook install should be refreshed');
  assert.equal(managed[0].command, 'engram agent-hook --host claude');
  assert.equal(managed[0].timeout, 10000);

  await rm(cwd, { recursive: true, force: true });
});

test('auto-upgrade can be skipped for one command', async () => {
  const { cwd, env } = await tempWorkspace('engram-cli-autoupgrade-skip-');
  const init = await runEngram(cwd, env, ['inject', '--no-skillset']);
  assert.equal(init.code, 0, init.stderr);
  const configFile = path.join(workspaceMemoryRoot(cwd), 'engram.config.json');
  const config = JSON.parse(await readFile(configFile, 'utf8'));
  config.version = '0.0.0';
  config.auto_upgrade = { version: '0.0.0', checked_at: '2026-01-01T00:00:00.000Z' };
  await writeFile(configFile, `${JSON.stringify(config, null, 2)}\n`);
  const skipped = await runEngram(cwd, env, ['load', '--dry-run', '--no-auto-upgrade', 'skip auto upgrade']);
  assert.equal(skipped.code, 0, skipped.stderr);
  const unchanged = JSON.parse(await readFile(configFile, 'utf8'));
  assert.equal(unchanged.auto_upgrade.version, '0.0.0');
  await rm(cwd, { recursive: true, force: true });
});





