/** Package-wide constants and deterministic starter content. */
import { VERSION } from './version.js';

export { VERSION };
export const AGENTS_DIR = '.agents';
export const ENGRAM_DIR = '.agents/.engram';
export const LEGACY_ENGRAM_DIR = '.engram';
export const INDEX_FILE = 'memory.index.json';
export const GRAPH_FILE = 'memory.graph.json';
export const VECTOR_DB_FILE = 'memory.vec.sqlite';
export const VECTOR_DB_SCHEMA_VERSION = 1;
export const HASH_FILE = 'memory.hashes.json';
export const CHANGELOG_FILE = 'changelog.md';
export const HELP_FILE = 'HELP.md';
export const README_FILE = 'README.md';
export const REVIEW_DIR = 'review';

export const MEMORY_DIRS = ['rules', 'skills', 'knowledge', 'archive', 'quarantine', 'proposals', 'inbox'];

export const DEFAULT_IGNORE = `# Engram ignores private or generated AI context.
.env
.env.*
dist/
coverage/
node_modules/
*.secret
private/**
`;

export const GENERATED_HEADER =
  `<!-- Auto-generated by engram v${VERSION} - do not edit directly. Edit .agents/.engram/ instead. -->`;
