/** Package-wide constants and deterministic starter content. */
export const VERSION = '0.0.1';
export const ENGRAM_DIR = '.engram';
export const INDEX_FILE = 'memory.index.json';
export const HASH_FILE = 'memory.hashes.json';
export const CHANGELOG_FILE = 'changelog.md';
export const HELP_FILE = 'HELP.md';
export const README_FILE = 'README.md';

export const MEMORY_DIRS = ['rules', 'skills', 'knowledge', 'archive', 'quarantine', 'proposals'];

export const DEFAULT_IGNORE = `# Engram ignores private or generated AI context.
.env
.env.*
dist/
coverage/
node_modules/
*.secret
private/**
`;

export const GENERATED_HEADER =
  '<!-- Auto-generated by engram v0.0.1 - do not edit directly. Edit .engram/ instead. -->';
