/** Shell completion script rendering for the CLI command surface. */
import { commandNames } from './command-registry.js';
/** Return a shell completion script for the current command surface. */
export function completionScript(shell: 'bash' | 'zsh' | 'powershell' = 'bash'): string {
  const commands = commandNames().join(' ');
  const saveTypes = ['rule', 'skill', 'workflow', 'knowledge'].join(' ');
  const scopes = ['workspace', 'global', 'both'].join(' ');
  const formats = ['agents-md', 'claude-md', 'cursorrules'].join(' ');
  const shells = ['bash', 'zsh', 'powershell'].join(' ');
  const ruleVariants = ['off', 'light', 'balanced', 'strict', 'status'].join(' ');
  const readModes = ['startup', 'auto', 'always', 'manual', 'off', 'status'].join(' ');
  const proofModes = ['off', 'compact', 'status'].join(' ');
  const saveTargets = ['workspace', 'global', 'both', 'status'].join(' ');
  const loadLimits = ['status', 'reset', '8', '12', '16', '24', '32'].join(' ');
  const profileActions = ['status', 'list', 'create', 'use', 'remove', 'merge'].join(' ');
  const ignoreActions = ['status', 'check', 'add'].join(' ');
  const workspaceActions = ['list', 'info', 'set', 'unregister', 'link', 'unlink'].join(' ');
  const configActions = ['view', 'set'].join(' ');
  const saveSessionArgs = ['--file', '--scope', '--profile', '--role', '--roles', '--query-level', '--accept-all', '--show-rule-variants'].join(' ');
  const observeArgs = ['--file', '--scope', '--profile', '--role', '--roles', '--propose', '--accept-all'].join(' ');
  const takeControlArgs = ['--file', '--dir', '--include', '--exclude', '--max-sources', '--max-chars', '--scope', '--profile', '--role', '--roles', '--all', '--accept-all', '--metacognize', '--dry-run', '--plan'].join(' ');
  const metacognizeArgs = ['--workspace', '--global', '--all', '--accept-all', '--dry-run'].join(' ');
  const resolveConflictArgs = ['--dry-run', '--metacognize', '--accept-all'].join(' ');
  const upgradeArgs = ['--plan', '--latest', '--self', '--memory-only', '--global-skillsets-only', '--target', '--force', '--no-version-check', '--no-auto-upgrade'].join(' ');
  const globalFolderArgs = ['--move-from-path'].join(' ');
  const cloneMemoryArgs = ['workspace', 'global', '--force', '--dry-run', '--metacognize', '--accept-all'].join(' ');
  const skillsetTargets = ['all', 'list', 'agents-md', 'codex', 'copilot', 'claude', 'cursor', 'gemini', 'cline', 'windsurf', 'opencode', 'open-code', 'mcp', 'slash'].join(' ');
  const agentHookTargets = ['all', 'codex', 'claude', 'gemini', 'cursor', 'copilot', 'cline', 'windsurf'].join(' ');
  if (shell === 'zsh') {
    return [
      '#compdef engram',
      '_engram() {',
      '  local -a commands',
      `  commands=(${commands})`,
      '  if (( CURRENT == 2 )); then',
      '    compadd -- "${commands[@]}"',
      '    return',
      '  fi',
      '  case $words[2] in',
      '    init|i)',
      `      _arguments "--force" "--global-only" "--scope[default save target]:scope:(${scopes})" "--no-skillset" "--skillset=[target]" "--submodule" "--submodule-remote=[git-url]" "--no-global" "--global-path=[path]" "--global-remote=[git-url]" "--global-branch=[branch]"`,
      '      ;;',
      `    completion|c)\n      _arguments "1:shell:(${shells})"\n      ;;`,
      '    profile|pf)',
      `      _arguments "--global-path[path]:path:_files -/" "--scope[default save target]:scope:(${scopes})" "--profile[run command with profile]:profile:" "--from-profile[source profile]:profile:" "--to-profile[target profile]:profile:" "--workspace[set workspace default]" "--user[set user default]" "--use[make created profile active]" "--force[overwrite profile or merge destination]" "--dry-run[preview merge only]" "1:action:(${profileActions})"`,
      '      ;;',
      '    update-global-folder|ugf)\n      _arguments "--move-from-path[old global root]:path:_files -/" "1:new global root:_files -/"\n      ;;',
      '    save|s)',
      `      _arguments "--scope[write scope]:scope:(${scopes})" "--profile[run with profile]:profile:" "--role[role tag]:role:" "--roles[comma-separated roles]:roles:" "--show-rule-variants[show stored rule variant blocks in previews]" "1:memory type:(${saveTypes})"`,
      '      ;;',
      '    save-session|ss)',
      `      _arguments "--file[read session summary file]:file:_files" "--scope[write scope]:scope:(${scopes})" "--profile[run with profile]:profile:" "--role[role tag]:role:" "--roles[comma-separated roles]:roles:" "--query-level[recent chat sessions to mine]:number:" "--accept-all[accept every save-session candidate]" "1:session summary: "`,
      '      ;;',
      '    observe|o)',
      `      _arguments "--file[read raw note file]:file:_files" "--scope[write scope]:scope:(${scopes})" "--profile[run with profile]:profile:" "--role[role tag]:role:" "--roles[comma-separated roles]:roles:" "--propose[mine inbox note through save-session]" "--accept-all[accept every proposed candidate]" "1:note: "`,
    '      ;;',
    '    take-control|tc)',
      `      _arguments "--file[read one source file]:file:_files" "--dir[scan one source directory]:dir:_files -/" "--include[include matching glob]:glob:" "--exclude[exclude matching glob]:glob:" "--max-sources[maximum source count]:number:" "--max-chars[maximum chars per source]:number:" "--scope[write scope]:scope:(${scopes})" "--profile[run with profile]:profile:" "--role[role tag]:role:" "--roles[comma-separated roles]:roles:" "--all[include README docs and library docs]" "--accept-all[accept every generated candidate]" "--metacognize[pause accept-all writes for related-memory restructuring]" "--dry-run[show source pack only]" "--plan[preview source plan only]"`,
      '      ;;',
      '    metacognize|mc)',
      '      _arguments "--workspace[restructure workspace memory]" "--global[restructure global memory]" "--all[restructure workspace and global memory]" "--accept-all[accept every generated restructure candidate when human requested]" "--dry-run[show source pack or candidate preview without writing]"',
      '      ;;',
      '    load|l)\n      _arguments "--all" "--dry-run" "--for-agents[slim memory output for AI agents]" "1:query: "\n      ;;',
      '    graph|g)\n      _arguments "--rebuild" "1:query: "\n      ;;',
      '    archive|ar)\n      _arguments "--reason[archive reason]:reason:" "1:memory: "\n      ;;',
      '    benchmark|bm)\n      _arguments "1:cases file:_files"\n      ;;',
      '    search|f)\n      _arguments "1:query: "\n      ;;',
      '    verify|vf|rehash|rh|rebuild-index|ri|repair|rp)',
      `      _arguments "1:scope:(${scopes})"`,
      '      ;;',
      '    export|x)',
      `      _arguments "--format[output format]:format:(${formats})"`,
      '      ;;',
      '    ignore|ig)',
      `      _arguments "1:action:(${ignoreActions})"`,
      '      ;;',
      '    set-rule-variant|rv)',
      `      _arguments "1:variant:(${ruleVariants})"`,
      '      ;;',
      '    set-save-target)',
      `      _arguments "1:target:(${saveTargets})"`,
      '      ;;',
    '    set-proof|sp)',
      `      _arguments "1:mode:(${proofModes})"`,
      '      ;;',
    '    set-load-limit|ll)',
      `      _arguments "1:limit:(${loadLimits})"`,
    '      ;;',
    '    set-read|rd)',
      `      _arguments "1:mode:(${readModes})"`,
      '      ;;',
    '    resolve-conflicts|rc)',
      '      _arguments "--dry-run[preview conflicts]" "--metacognize[run workspace metacognition after conflict handling]" "--accept-all[accept generated metacognize candidates when human requested]"',
      '      ;;',
      `      _arguments "--global" "--plan" "--force" "1:target:(${agentHookTargets})"`,
      '      ;;',
      `      _arguments "--global" "1:target:(${agentHookTargets})"`,
      '      ;;',
      '    agent-hook)',
      '      _arguments "--host[hook host]:host:(codex claude gemini)"',
      '      ;;',
      '    link|is)',
      `      _arguments "--global" "--force" "1:target:(${skillsetTargets})"`,
      '      ;;',
      '    unlink)',
      '      _arguments "--global" "--force" "1:target:(all agents-md copilot claude cursor gemini cline windsurf agent-skill antigravity opencode mcp slash)"',
    '      ;;',
    '    clone-memory|cm)',
      '      _arguments "--force[overwrite existing destination files]" "--dry-run[preview clone or proposal plan]" "--metacognize[route clone candidates through save-session approval]" "--accept-all[accept every metacognize candidate when human requested]" "1:source:(workspace global)" "2:target:(workspace global)"',
      '      ;;',
      '    workspace|ws)',
      `      _arguments "1:action:(${workspaceActions})"`,
      '      ;;',
      '    config|cfg)',
      `      _arguments "1:action:(${configActions})"`,
      '      ;;',
      '    upgrade|up)',
      `      _arguments "--plan" "--latest" "--self" "--memory-only" "--global-skillsets-only" "--target=[agent]:agent:(${skillsetTargets})" "--force" "--no-version-check"`,
      '      ;;',
      '  esac',
      '}',
      'compdef _engram engram'
    ].join('\n');
  }
  if (shell === 'powershell') {
    return [
      '$engramCommands = @(',
      commandNames().map((command) => `  '${command}'`).join(',\n'),
      ')',
      '$engramInitArgs = @(\'--force\', \'--global-only\', \'--scope\', \'--no-skillset\', \'--skillset\', \'--submodule\', \'--submodule-remote\', \'--no-global\', \'--global-path\', \'--global-remote\', \'--global-branch\')',
      '$engramSaveTypes = @(\'rule\', \'skill\', \'workflow\', \'knowledge\', \'--scope\', \'--profile\', \'--role\', \'--roles\', \'--show-rule-variants\')',
      `$engramSaveSessionArgs = @(${saveSessionArgs.split(' ').map((arg) => `'${arg}'`).join(', ')})`,
      `$engramObserveArgs = @(${observeArgs.split(' ').map((arg) => `'${arg}'`).join(', ')})`,
      `$engramTakeControlArgs = @(${takeControlArgs.split(' ').map((arg) => `'${arg}'`).join(', ')})`,
      `$engramMetacognizeArgs = @(${metacognizeArgs.split(' ').map((arg) => `'${arg}'`).join(', ')})`,
      `$engramResolveConflictArgs = @(${resolveConflictArgs.split(' ').map((arg) => `'${arg}'`).join(', ')})`,
      `$engramUpgradeArgs = @(${upgradeArgs.split(' ').map((arg) => `'${arg}'`).join(', ')})`,
      `$engramGlobalFolderArgs = @(${globalFolderArgs.split(' ').map((arg) => `'${arg}'`).join(', ')})`,
      `$engramCloneMemoryArgs = @(${cloneMemoryArgs.split(' ').map((arg) => `'${arg}'`).join(', ')})`,
      `$engramProfileActions = @(${profileActions.split(' ').map((arg) => `'${arg}'`).join(', ')})`,
      `$engramWorkspaceActions = @(${workspaceActions.split(' ').map((arg) => `'${arg}'`).join(', ')})`,
      `$engramConfigActions = @(${configActions.split(' ').map((arg) => `'${arg}'`).join(', ')})`,
      `$engramSkillsetTargets = @(${skillsetTargets.split(' ').map((target) => `'${target}'`).join(', ')})`,
      `$engramAgentHookTargets = @(${agentHookTargets.split(' ').map((target) => `'${target}'`).join(', ')})`,
      '$engramScopes = @(\'workspace\', \'global\', \'both\')',
      '$engramRuleVariants = @(\'off\', \'light\', \'balanced\', \'strict\', \'status\')',
      `$engramProofModes = @(${proofModes.split(' ').map((arg) => `'${arg}'`).join(', ')})`,
      `$engramReadModes = @(${readModes.split(' ').map((arg) => `'${arg}'`).join(', ')})`,
      '$engramSaveTargets = @(\'workspace\', \'global\', \'both\', \'status\')',
      `$engramLoadLimits = @(${loadLimits.split(' ').map((arg) => `'${arg}'`).join(', ')})`,
      'Register-ArgumentCompleter -Native -CommandName engram -ScriptBlock {',
      '  param($wordToComplete, $commandAst, $cursorPosition)',
      '  $words = @($commandAst.CommandElements | ForEach-Object { $_.ToString() })',
      '  $command = if ($words.Count -ge 2) { $words[1] } else { "" }',
      '  $previous = if ($words.Count -ge 2) { $words[$words.Count - 2] } else { "" }',
      '  $choices = switch ($previous) {',
      '    "--scope" { $engramScopes; break }',
      '    "--profile" { break }',
      '    "--from-profile" { break }',
      '    "--to-profile" { break }',
      '    "--skillset" { $engramSkillsetTargets; break }',
      '    "--target" { $engramSkillsetTargets; break }',
      '    "--host" { @(\'codex\', \'claude\', \'gemini\'); break }',
      '    "--format" { @(\'agents-md\', \'claude-md\', \'cursorrules\'); break }',
      '    "--file" { break }',
      '    "--role" { break }',
      '    "--roles" { break }',
      '    "--query-level" { break }',
      '    "--move-from-path" { break }',
      '    default {',
      '      switch ($command) {',
      '        { $_ -in @(\'init\', \'i\') } { $engramInitArgs; break }',
      '        { $_ -in @(\'profile\', \'pf\') } { $engramProfileActions + \'--global-path\' + \'--scope\' + \'--workspace\' + \'--user\' + \'--use\' + \'--force\' + \'--dry-run\' + \'--from-profile\' + \'--to-profile\'; break }',
      '        { $_ -in @(\'save\', \'s\') } { $engramSaveTypes; break }',
      '        { $_ -in @(\'save-session\', \'ss\') } { $engramSaveSessionArgs; break }',
      '        { $_ -in @(\'observe\', \'o\') } { $engramObserveArgs; break }',
      '        { $_ -in @(\'take-control\', \'tc\') } { $engramTakeControlArgs; break }',
      '        { $_ -in @(\'metacognize\', \'mc\') } { $engramMetacognizeArgs; break }',
      '        { $_ -in @(\'resolve-conflicts\', \'rc\') } { $engramResolveConflictArgs; break }',
      '        { $_ -in @(\'update-global-folder\', \'ugf\') } { $engramGlobalFolderArgs; break }',
      '        { $_ -in @(\'clone-memory\', \'cm\') } { $engramCloneMemoryArgs; break }',
      '        { $_ -in @(\'link\', \'is\') } { $engramSkillsetTargets + \'--global\' + \'--force\'; break }',
      '        { $_ -eq \'unlink\' } { $engramSkillsetTargets + \'--global\' + \'--force\'; break }',
      '        { $_ -in @(\'upgrade\', \'up\') } { $engramUpgradeArgs; break }',
      '        { $_ -in @(\'set-rule-variant\', \'rv\') } { $engramRuleVariants; break }',
      '        { $_ -in @(\'set-save-target\') } { $engramSaveTargets; break }',
      '        { $_ -in @(\'set-proof\', \'sp\') } { $engramProofModes; break }',
      '        { $_ -in @(\'set-load-limit\', \'ll\') } { $engramLoadLimits; break }',
      '        { $_ -in @(\'set-read\', \'rd\') } { $engramReadModes; break }',
      '        { $_ -eq \'agent-hook\' } { @(\'--host\'); break }',
      '        { $_ -in @(\'workspace\', \'ws\') } { $engramWorkspaceActions; break }',
      '        { $_ -in @(\'config\', \'cfg\') } { $engramConfigActions; break }',
      '        { $_ -in @(\'verify\', \'vf\', \'rebuild-index\', \'ri\', \'repair\', \'rp\') } { $engramScopes; break }',
      '        default { $engramCommands }',
      '      }',
      '    }',
      '  }',
      '  $choices | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {',
      '    [System.Management.Automation.CompletionResult]::new($_, $_, "ParameterValue", $_)',
      '  }',
      '}'
    ].join('\n');
  }
  return [
    '_engram() {',
    '  local cur prev words cword',
    '  if declare -F _init_completion >/dev/null; then',
    '    _init_completion || return',
    '  else',
    '    cur="${COMP_WORDS[COMP_CWORD]}"',
    '    prev="${COMP_WORDS[COMP_CWORD-1]}"',
    '    words=("${COMP_WORDS[@]}")',
    '    cword=$COMP_CWORD',
    '  fi',
    `  local commands="${commands}"`,
    `  local save_types="${saveTypes}"`,
    `  local scopes="${scopes}"`,
    `  local formats="${formats}"`,
    `  local shells="${shells}"`,
    `  local rule_variants="${ruleVariants}"`,
    `  local proof_modes="${proofModes}"`,
    `  local read_modes="${readModes}"`,
    `  local save_targets="${saveTargets}"`,
    `  local load_limits="${loadLimits}"`,
    `  local profile_actions="${profileActions}"`,
    `  local ignore_actions="${ignoreActions}"`,
    `  local workspace_actions="${workspaceActions}"`,
    `  local config_actions="${configActions}"`,
    `  local upgrade_args="${upgradeArgs}"`,
    `  local metacognize_args="${metacognizeArgs}"`,
    `  local resolve_conflict_args="${resolveConflictArgs}"`,
    `  local global_folder_args="${globalFolderArgs}"`,
    `  local clone_memory_args="${cloneMemoryArgs}"`,
    `  local skillset_targets="${skillsetTargets}"`,
    `  local agent_hook_targets="${agentHookTargets}"`,
    '  case "$prev" in',
    '    --format)',
    '      COMPREPLY=( $(compgen -W "$formats" -- "$cur") )',
    '      return',
    '      ;;',
    '    --scope)',
    '      COMPREPLY=( $(compgen -W "$scopes" -- "$cur") )',
    '      return',
    '      ;;',
    '    --profile|--from-profile|--to-profile)',
    '      COMPREPLY=()',
    '      return',
    '      ;;',
    '    --global-path)',
    '      COMPREPLY=( $(compgen -f -- "$cur") )',
    '      return',
    '      ;;',
    '    --skillset)',
    '      COMPREPLY=( $(compgen -W "$skillset_targets" -- "$cur") )',
    '      return',
    '      ;;',
    '    --target)',
      '      COMPREPLY=( $(compgen -W "$skillset_targets" -- "$cur") )',
      '      return',
      '      ;;',
    '    --host)',
      '      COMPREPLY=( $(compgen -W "codex claude gemini" -- "$cur") )',
      '      return',
      '      ;;',
    '    --file|--dir)',
      '      COMPREPLY=( $(compgen -f -- "$cur") )',
      '      return',
      '      ;;',
    '    --move-from-path)',
    '      COMPREPLY=( $(compgen -f -- "$cur") )',
    '      return',
    '      ;;',
    '    --role|--roles|--query-level)',
    '      COMPREPLY=()',
    '      return',
    '      ;;',
    '  esac',
    '  case "${words[1]}" in',
    '    init|i)',
    '      COMPREPLY=( $(compgen -W "--force --global-only --scope --no-skillset --skillset --submodule --submodule-remote --no-global --global-path --global-remote --global-branch" -- "$cur") )',
    '      return',
    '      ;;',
    '    completion|c)',
    '      if [[ $cword -eq 2 ]]; then COMPREPLY=( $(compgen -W "$shells" -- "$cur") ); return; fi',
    '      COMPREPLY=()',
    '      return',
    '      ;;',
    '    update-global-folder|ugf)',
    '      COMPREPLY=( $(compgen -W "$global_folder_args" -- "$cur") )',
    '      return',
    '      ;;',
    '    profile|pf)',
    '      if [[ $cword -eq 2 ]]; then COMPREPLY=( $(compgen -W "$profile_actions" -- "$cur") ); return; fi',
    '      COMPREPLY=( $(compgen -W "--global-path --scope --workspace --user --use --force --dry-run --from-profile --to-profile" -- "$cur") )',
    '      return',
    '      ;;',
    '    save|s)',
    '      if [[ $cword -eq 2 ]]; then COMPREPLY=( $(compgen -W "$save_types --scope --profile --role --roles --show-rule-variants" -- "$cur") ); return; fi',
    '      COMPREPLY=( $(compgen -W "--scope --profile --role --roles --show-rule-variants" -- "$cur") )',
      '      return',
      '      ;;',
    '    save-session|ss)',
    '      COMPREPLY=( $(compgen -W "--file --scope --profile --role --roles --query-level --accept-all --show-rule-variants" -- "$cur") )',
      '      return',
      '      ;;',
    '    observe|o)',
    '      COMPREPLY=( $(compgen -W "--file --scope --profile --role --roles --propose --accept-all" -- "$cur") )',
      '      return',
      '      ;;',
    '    take-control|tc)',
    '      COMPREPLY=( $(compgen -W "--file --dir --include --exclude --max-sources --max-chars --scope --profile --role --roles --all --accept-all --metacognize --dry-run --plan" -- "$cur") )',
    '      return',
    '      ;;',
    '    metacognize|mc)',
    '      COMPREPLY=( $(compgen -W "$metacognize_args" -- "$cur") )',
    '      return',
    '      ;;',
    '    load|l)',
    '      # --all: bypass compact cap (broad context), --dry-run: preview without printing, --for-agents: slim agent output',
    '      COMPREPLY=( $(compgen -W "--all --dry-run --for-agents" -- "$cur") )',
    '      return',
    '      ;;',
    '    graph|g)',
    '      COMPREPLY=( $(compgen -W "--rebuild" -- "$cur") )',
    '      return',
    '      ;;',
    '    archive|ar)',
    '      COMPREPLY=( $(compgen -W "--reason" -- "$cur") )',
    '      return',
    '      ;;',
    '    verify|vf|rehash|rh|rebuild-index|ri|repair|rp)',
    '      if [[ $cword -eq 2 ]]; then COMPREPLY=( $(compgen -W "$scopes" -- "$cur") ); return; fi',
    '      COMPREPLY=()',
    '      return',
    '      ;;',
    '    export|x)',
    '      COMPREPLY=( $(compgen -W "--format" -- "$cur") )',
    '      return',
    '      ;;',
    '    ignore|ig)',
    '      if [[ $cword -eq 2 ]]; then COMPREPLY=( $(compgen -W "$ignore_actions" -- "$cur") ); return; fi',
    '      COMPREPLY=()',
    '      return',
    '      ;;',
    '    set-rule-variant|rv)',
    '      if [[ $cword -eq 2 ]]; then COMPREPLY=( $(compgen -W "$rule_variants" -- "$cur") ); return; fi',
    '      COMPREPLY=()',
    '      return',
    '      ;;',
    '    set-save-target)',
    '      if [[ $cword -eq 2 ]]; then COMPREPLY=( $(compgen -W "$save_targets" -- "$cur") ); return; fi',
    '      COMPREPLY=()',
    '      return',
    '      ;;',
    '    set-proof|sp)',
      '      if [[ $cword -eq 2 ]]; then COMPREPLY=( $(compgen -W "$proof_modes" -- "$cur") ); return; fi',
      '      COMPREPLY=()',
      '      return',
      '      ;;',
    '    set-load-limit|ll)',
      '      if [[ $cword -eq 2 ]]; then COMPREPLY=( $(compgen -W "$load_limits" -- "$cur") ); return; fi',
      '      COMPREPLY=()',
      '      return',
      '      ;;',
    '    set-read|rd)',
      '      if [[ $cword -eq 2 ]]; then COMPREPLY=( $(compgen -W "$read_modes" -- "$cur") ); return; fi',
      '      COMPREPLY=()',
      '      return',
      '      ;;',
    '    resolve-conflicts|rc)',
      '      COMPREPLY=( $(compgen -W "$resolve_conflict_args" -- "$cur") )',
      '      return',
      '      ;;',
      '      COMPREPLY=( $(compgen -W "--global --plan --force" -- "$cur") )',
      '      return',
      '      ;;',
      '      COMPREPLY=( $(compgen -W "--global" -- "$cur") )',
      '      return',
      '      ;;',
    '    agent-hook)',
      '      COMPREPLY=( $(compgen -W "--host" -- "$cur") )',
      '      return',
      '      ;;',
    '    clone-memory|cm)',
    '      COMPREPLY=( $(compgen -W "$clone_memory_args" -- "$cur") )',
    '      return',
    '      ;;',
    '    link|is)',
    '      if [[ $prev == link || $prev == is ]]; then COMPREPLY=( $(compgen -W "$skillset_targets --global --force" -- "$cur") ); return; fi',
    '      COMPREPLY=( $(compgen -W "--global --force" -- "$cur") )',
    '      return',
    '      ;;',
    '    unlink)',
    '      if [[ $prev == unlink ]]; then COMPREPLY=( $(compgen -W "$skillset_targets --global --force" -- "$cur") ); return; fi',
    '      COMPREPLY=( $(compgen -W "--global --force" -- "$cur") )',
    '      return',
    '      ;;',
    '    upgrade|up)',
    '      COMPREPLY=( $(compgen -W "$upgrade_args" -- "$cur") )',
    '      return',
    '      ;;',
    '    workspace|ws)',
    `      if [[ $cword -eq 2 ]]; then COMPREPLY=( $(compgen -W "${workspaceActions}" -- "$cur") ); return; fi`,
    '      COMPREPLY=()',
    '      return',
    '      ;;',
    '    config|cfg)',
    `      if [[ $cword -eq 2 ]]; then COMPREPLY=( $(compgen -W "${configActions}" -- "$cur") ); return; fi`,
    '      COMPREPLY=()',
    '      return',
    '      ;;',
    '  esac',
    '  COMPREPLY=( $(compgen -W "$commands" -- "$cur") )',
    '}',
    'complete -F _engram engram'
  ].join('\n');
}
