/** Detailed command help shown by `engram help <topic>`. */
export type CommandTopicHelp = {
  title: string;
  summary: string;
  useCases: string[];
  examples: string[];
  notes?: string[];
  aliases?: string[];
};

export const COMMAND_TOPICS: Record<string, CommandTopicHelp> = {
  '--version': topic('engram --version', 'Print the current Engram CLI version.', ['Check which build is installed before reporting an issue.'], ['engram --version', 'engram -v'], ['This reads the package-wide VERSION constant.'], ['version', '-v']),
  init: topic('engram init', 'Create or refresh workspace and global memory roots.', ['Start using Engram in a repository.', 'Configure shared global memory through a Git remote.', 'Create `.engram` as a submodule when a team wants memory versioned separately.'], ['engram init', 'engram init --submodule', 'engram init --global-remote https://github.com/example/team-engram.git'], ['Interactive terminals ask before optional remote and submodule setup.']),
  help: topic('engram help', 'Show command help. Add a topic for deeper command-specific guidance.', ['Learn a command before running it.', 'Find examples for aliases, save flows, or operational commands.'], ['engram help', 'engram help set-role', 'engram -h autosave', 'engram save -h'], ['The overview stays short; topic help explains intent and examples.'], ['h', '-h']),
  'update-help': topic('engram update-help', 'Regenerate the workspace `.engram/HELP.md` cache from the command registry.', ['Refresh generated help after upgrading Engram.', 'Keep checked-in workspace help aligned with the CLI.'], ['engram update-help', 'engram uh'], ['This writes inside `.engram`; it does not change memory entries.'], ['uh']),
  entry: topic('engram entry', 'Show runtime configuration, memory roots, and global Git state.', ['Debug which global memory folder is active.', 'Confirm configured vs detected global Git branch.', 'Check whether live sync, roles, or rule variants are enabled.'], ['engram entry', 'engram e'], ['Use this before changing Git remotes or diagnosing unexpected memory routing.'], ['e']),
  completion: topic('engram completion', 'Print shell completion scripts for Tab suggestions.', ['Enable command suggestions in bash, zsh, or PowerShell.', 'Discover subcommands and common flags faster.'], ['source <(engram completion bash)', 'source <(engram completion zsh)', 'engram completion powershell', 'engram c bash'], ['The command prints the script; add it to your shell startup file when you want it loaded every session.'], ['c']),
  save: topic('engram save', 'Propose one durable memory and save it only after A/B/C approval.', ['Capture a user correction as a rule.', 'Capture an objective project fact as knowledge.', 'Capture a repeatable procedure as a workflow/skill.', 'Attach role tags with `--role` or `--roles` so routing can filter frontend, backend, docs, or security memory.', 'Let Engram auto-detect the type from concise text.'], ['engram save "Always use pnpm in this repo"', 'engram save rule --role frontend "Never hand-roll spacing; use design tokens"', 'engram save knowledge "The app deploys through Vercel"', 'engram save workflow "When releasing, run tests, update changelog, tag version"'], ['For long sessions with several candidates, use `engram autosave`; if you decline that suggestion, normal save captures the best single candidate.'], ['s', 'rule', 'skill', 'workflow', 'knowledge']),
  autosave: topic('engram autosave', 'Propose multiple memories from a long session summary or agent brainstorm.', ['Mine a long human-agent interaction for several rules, knowledge facts, and workflows.', 'Read a transcript or summary from `--file transcript.md`.', 'Accept all candidates or only selected numbers such as `A 1,3`.', 'Keep automatic capture human-approved.'], ['engram autosave', 'engram autosave --file transcript.md', 'engram autosave --role frontend "TYPE: rule | TEXT: Always run tests before release."', 'engram as --scope workspace'], ['Agents should provide one candidate per line using `TYPE: ... | TEXT: ...`.'], ['as']),
  load: topic('engram load', 'Route and print memories relevant to the current task.', ['Start an agent session with relevant project memory.', 'Load only the context needed for a specific task.', 'Use `--all` when you intentionally want broad context.'], ['engram load "deployment workflow"', 'engram load --all', 'engram l "React styling"'], ['Low-confidence memories are skipped unless explicitly loaded through manual paths.'], ['l']),
  'dry-run': topic('engram dry-run', 'Preview which memory files would load without printing their contents.', ['Check routing before exposing memory content.', 'Debug why a query selects certain files.', 'Verify ignore and role filters.'], ['engram dry-run "auth hardening"', 'engram dr --all'], ['This is useful for safe inspection in shared terminals.'], ['dr']),
  search: topic('engram search', 'Search visible indexed memories.', ['Find whether a fact or rule already exists.', 'Locate duplicate or stale memory before saving.', 'Audit topic coverage.'], ['engram search "pnpm"', 'engram f "deployment"'], ['Search uses the visible index, so ignored memories stay hidden.'], ['f']),
  verify: topic('engram verify', 'Verify memory hashes for workspace and global scopes.', ['Detect hand-edited or tampered memory files.', 'Run before committing memory changes.', 'Check only one scope when debugging.'], ['engram verify', 'engram verify workspace', 'engram vf global'], ['Hash mismatches make `load` skip unsafe content.'], ['vf']),
  'rebuild-index': topic('engram rebuild-index', 'Rebuild memory indexes from Markdown files.', ['Recover after index files were deleted.', 'Refresh indexes after approved manual cleanup.', 'Debug missing search/load results.'], ['engram rebuild-index', 'engram rebuild-index workspace', 'engram ri global'], ['Invalid memory files are skipped during rebuild.'], ['ri']),
  audit: topic('engram audit', 'List visible memories with optional author, stale, and confidence filters.', ['Find old memories that may need review.', 'Show memories owned by a teammate.', 'Inspect low-confidence candidates.'], ['engram audit', 'engram audit --stale', 'engram audit --author dev@example.com', 'engram a --low-confidence'], ['Audit reports metadata rows, not full memory content.'], ['a']),
  health: topic('engram health', 'Summarize memory health metrics.', ['Check memory coverage and quality trends.', 'Spot unhealthy memory stores before sharing.', 'Prepare for team review.'], ['engram health', 'engram he'], ['Use with `quality-check` for deeper quality signals.'], ['he']),
  'quality-check': topic('engram quality-check', 'Evaluate visible memory quality and potential issues.', ['Find vague or low-value memories.', 'Improve memory before exporting to agents.', 'Review memory hygiene during maintenance.'], ['engram quality-check', 'engram qc'], ['Quality checks are advisory; they do not write files.'], ['qc']),
  stats: topic('engram stats', 'Show counts and summary statistics for visible memories.', ['Confirm a save increased memory count.', 'Compare workspace and global memory volume.', 'Check whether ignore rules are hiding entries.'], ['engram stats', 'engram st'], ['Stats respect visibility filters.'], ['st']),
  deduplicate: topic('engram deduplicate', 'Detect similar or duplicate visible memories.', ['Find repeated rules before they confuse agents.', 'Clean up after imports or team merges.', 'Prepare memory for a release.'], ['engram deduplicate', 'engram dd'], ['Semantic dedupe is not supported yet; current matching is deterministic.'], ['dd']),
  export: topic('engram export', 'Export visible memory to agent instruction formats or a JSON bundle.', ['Generate AGENTS.md, CLAUDE.md, or Cursor rules.', 'Share a reviewable bundle.', 'Feed memory into an agent without runtime integration.'], ['engram export --format agents-md', 'engram export --format claude-md', 'engram x --format cursorrules'], ['Exports skip ignored or unsafe memory.'], ['x']),
  import: topic('engram import', 'Import a memory bundle through the approval gate.', ['Review memory from another workspace.', 'Move memory between machines.', 'Merge team memory with human oversight.'], ['engram import bundle.json', 'engram im team-memory.json'], ['Imports should never bypass approval.'], ['im']),
  ignore: topic('engram ignore', 'Manage ignore rules for memory visibility.', ['Hide private or noisy memory from routing.', 'Check whether a path is ignored.', 'Add project-specific ignore patterns.'], ['engram ignore status', 'engram ignore check knowledge/private.md', 'engram ignore add private/**', 'engram ig status'], ['Ignore rules affect search, load, export, and stats.'], ['ig']),
  'set-role': topic('engram set-role', 'Configure active developer roles for context routing.', ['Load frontend-only memory during UI work.', 'Load backend and security memory during auth work.', 'Clear roles when you want unfiltered routing.'], ['engram set-role frontend design', 'engram set-role backend security', 'engram set-role docs', 'engram set-role'], ['When roles are set, memories with non-matching `role: [...]` frontmatter are skipped. With no active roles, role filtering is disabled.'], ['sr', 'role', 'roles', 'set-roles']),
  'set-rule-variant': topic('engram set-rule-variant', 'Tune how strict rule memories render for agents.', ['Use strict for lower-tier models that need stronger guardrails.', 'Use light or balanced for top-tier models so rules do not limit their reasoning power.', 'Turn variants off when compact output is preferred.'], ['engram set-rule-variant strict', 'engram set-rule-variant balanced', 'engram set-rule-variant off', 'engram rv status'], ['This affects rendered rule output for load/export/sync.'], ['rv', 'rule-variant']),
  'resolve-conflicts': topic('engram resolve-conflicts', 'Preview or resolve Engram-owned Git conflicts in memory files.', ['Inspect memory merge conflicts safely.', 'Resolve deterministic Engram-owned conflicts.', 'Avoid touching unrelated project files.'], ['engram resolve-conflicts --dry-run', 'engram resolve-conflicts', 'engram rc --dry-run'], ['Use `--dry-run` first when reviewing team memory conflicts.'], ['rc']),
  'install-hooks': topic('engram install-hooks', 'Install Git hooks for local Engram integrity checks.', ['Verify workspace memory before commits.', 'Resolve Engram memory conflicts after pulls.', 'Add guardrails to team workflows.'], ['engram install-hooks', 'engram ih'], ['Human-authored hooks are preserved unless generated by Engram.'], ['ih']),
  'install-skillset': topic('engram install-skillset', 'Generate agent-specific instruction files and slash adapters.', ['Install AGENTS.md instructions for Codex-compatible agents.', 'Install slash command adapters.', 'Configure MCP-capable clients.'], ['engram install-skillset all', 'engram install-skillset codex', 'engram install-skillset slash', 'engram is list'], ['Existing human-authored files are skipped unless `--force` is used.'], ['is']),
  sync: topic('engram sync', 'Sync global memory with Git and refresh enabled live-sync targets.', ['Pull/push shared global memory.', 'Refresh generated AGENTS.md or Cursor rule targets.', 'Keep team memory current after approved saves.'], ['engram sync', 'engram sy'], ['Live sync targets must be enabled in config.'], ['sy']),
  propose: topic('engram propose', 'Create a review-oriented proposal for a memory file.', ['Prepare a memory change for PR review.', 'Ask a teammate to approve a memory update.', 'Preview a specific memory file with context.'], ['engram propose .engram/knowledge/deploy.md', 'engram p .engram/rules/use-pnpm.md'], ['This produces proposal text; it does not approve the memory by itself.'], ['p']),
  'team-dashboard': topic('engram team-dashboard', 'Summarize memory ownership and team coverage.', ['See who owns current memory.', 'Prepare team memory review.', 'Spot areas without shared context.'], ['engram team-dashboard', 'engram td'], ['Dashboard output depends on indexed visible memory.'], ['td'])
};

export function detailForTopic(rawTopic: string): CommandTopicHelp | undefined {
  const topic = rawTopic.toLowerCase().replace(/^engram\s+/, '').trim();
  return COMMAND_TOPICS[topic] ?? Object.values(COMMAND_TOPICS).find((item) => item.aliases?.includes(topic));
}

function topic(title: string, summary: string, useCases: string[], examples: string[], notes?: string[], aliases?: string[]): CommandTopicHelp {
  return { title, summary, useCases, examples, notes, aliases };
}
