/** Render the managed OpenCode plugin used for prompt-time Engram injection. */
export const OPENCODE_HOOK_PLUGIN_MARKER = '// Generated by Engram OpenCode hook installer. Edit with care.';

export function isGeneratedOpenCodeHookPlugin(content: string): boolean {
  return content.includes(OPENCODE_HOOK_PLUGIN_MARKER);
}

export function renderOpenCodeHookPlugin(): string {
  return `${OPENCODE_HOOK_PLUGIN_MARKER}
const HOOK_TIMEOUT_MS = 10000

export const EngramOpenCodePlugin = async ({ directory, $ }) => {
  const contexts = new Map()
  const started = new Set()

  const withTimeout = async (promise) => {
    let timer
    try {
      return await Promise.race([
        promise,
        new Promise((resolve) => {
          timer = setTimeout(() => resolve(null), HOOK_TIMEOUT_MS)
        }),
      ])
    } finally {
      if (timer) clearTimeout(timer)
    }
  }

  const runHook = async (sessionID, event, prompt = '') => {
    try {
      const payload = new Response(JSON.stringify({
        hook_event_name: event,
        session_id: sessionID,
        cwd: directory,
        prompt,
        source: 'opencode',
      }) + '\\n')
      const result = await withTimeout(
        $\`engram agent-hook --host opencode < \${payload}\`.nothrow().quiet()
      )
      if (!result || result.exitCode !== 0) return
      const parsed = JSON.parse(result.stdout.toString())
      const action = parsed?.engramHook?.action
      if (action === 'clear') {
        contexts.delete(sessionID)
        return
      }
      if (action !== 'replace') return
      const context = parsed?.hookSpecificOutput?.additionalContext
      if (typeof context === 'string' && context.trim()) contexts.set(sessionID, context)
    } catch {
      // Fail open: OpenCode continues without changing the last valid context.
    }
  }

  return {
    'chat.message': async (input, output) => {
      const sessionID = input.sessionID
      const prompt = output.parts
        .filter((part) => part.type === 'text' && !part.synthetic)
        .map((part) => part.text)
        .join('\\n')
        .trim()
      if (!started.has(sessionID)) {
        started.add(sessionID)
        await runHook(sessionID, 'SessionStart')
      }
      await runHook(sessionID, 'UserPromptSubmit', prompt)
    },
    'experimental.chat.system.transform': async (input, output) => {
      if (!input.sessionID) return
      const context = contexts.get(input.sessionID)
      if (context) output.system.push(context)
    },
    event: async ({ event }) => {
      if (event.type !== 'session.deleted') return
      const sessionID = event.properties?.info?.id
      if (!sessionID) return
      contexts.delete(sessionID)
      started.delete(sessionID)
    },
  }
}
`;
}
