import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdir, readFile, rm, stat, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { runEngram, tempWorkspace, workspaceMemoryRoot } from './helpers.mjs';

const GENERATED = '<!-- Generated by Engram skillset installer. Edit with care. -->';

function legacySkill() {
  return `---
id: legacy-deploy-flow
type: skill
scope: workspace
tags: [legacy, deploy]
author: test
confidence: high
---
# Legacy Deploy Flow

## Context

Old workspace used workflows directory.

## Content

- Run tests, build, then verify health.

## Example

engram load deploy
`;
}

test('init can run repeatedly and refresh generated skillset files', async () => {
  const { cwd, env } = await tempWorkspace('engram-init-');
  assert.equal((await runEngram(cwd, env, ['init'])).code, 0);
  await writeFile(path.join(cwd, 'AGENTS.md'), `${GENERATED}\n\n# Old Engram Agent Skillset\n`);
  await writeFile(path.join(cwd, '.agents', 'skills', 'engram', 'SKILL.md'), `---
name: engram
description: Old generated Engram skill
---
# Engram Memory Management Skill

Engram = workspace memory.
`);
  const second = await runEngram(cwd, env, ['init']);
  assert.equal(second.code, 0, second.stderr);
  assert.match(second.stdout, /engram already initialized/);
  assert.match(await readFile(path.join(cwd, 'AGENTS.md'), 'utf8'), /Default agent mode: compact/);
  assert.match(await readFile(path.join(cwd, '.agents', 'skills', 'engram', 'SKILL.md'), 'utf8'), /knowledge memory center/);
  assert.match(await readFile(path.join(cwd, '.agents', 'skills', 'engram', 'SKILL.md'), 'utf8'), /Session end/);
  assert.equal((await runEngram(cwd, env, ['init'])).code, 0);
  await rm(cwd, { recursive: true, force: true });
});

test('init migrates legacy .engram root under .agents', async () => {
  const { cwd, env } = await tempWorkspace('engram-init-');
  await mkdir(path.join(cwd, '.engram', 'rules'), { recursive: true });
  await writeFile(path.join(cwd, '.engram', 'engram.config.json'), JSON.stringify({ version: '0.0.0', scope: 'workspace' }, null, 2));
  await writeFile(path.join(cwd, '.engram', 'rules', 'legacy-location.md'), legacySkill().replace('type: skill', 'type: rule'));
  const migrated = await runEngram(cwd, env, ['init', '--no-skillset']);
  assert.equal(migrated.code, 0, migrated.stderr);
  assert.match(migrated.stdout, /workspace migrated from/);
  await stat(path.join(workspaceMemoryRoot(cwd), 'rules', 'legacy-location.md'));
  await assert.rejects(stat(path.join(cwd, '.engram')));
  await rm(cwd, { recursive: true, force: true });
});

test('init restores missing workspace scaffold files and directories', async () => {
  const { cwd, env } = await tempWorkspace('engram-init-');
  await runEngram(cwd, env, ['init']);
  await rm(path.join(workspaceMemoryRoot(cwd), 'proposals'), { recursive: true, force: true });
  await rm(path.join(workspaceMemoryRoot(cwd), 'HELP.md'), { force: true });
  await rm(path.join(workspaceMemoryRoot(cwd), 'README.md'), { force: true });
  await rm(path.join(workspaceMemoryRoot(cwd), 'memory.index.json'), { force: true });
  await rm(path.join(workspaceMemoryRoot(cwd), 'memory.hashes.json'), { force: true });
  const repaired = await runEngram(cwd, env, ['init']);
  assert.equal(repaired.code, 0, repaired.stderr);
  assert.match(repaired.stdout, /engram workspace reconciled/);
  await stat(path.join(workspaceMemoryRoot(cwd), 'proposals'));
  assert.match(await readFile(path.join(workspaceMemoryRoot(cwd), 'HELP.md'), 'utf8'), /--no-skillset/);
  assert.match(await readFile(path.join(workspaceMemoryRoot(cwd), 'README.md'), 'utf8'), /portable AI-agent memory/);
  assert.deepEqual(JSON.parse(await readFile(path.join(workspaceMemoryRoot(cwd), 'memory.hashes.json'), 'utf8')), {});
  await rm(cwd, { recursive: true, force: true });
});

test('init persists config migrations while preserving user settings', async () => {
  const { cwd, env } = await tempWorkspace('engram-init-');
  await runEngram(cwd, env, ['init']);
  await writeFile(path.join(workspaceMemoryRoot(cwd), 'engram.config.json'), JSON.stringify({
    version: '0.0.0',
    scope: 'workspace',
    roles: ['backend'],
    global_git: { branch: 'legacy' }
  }, null, 2));
  const migrated = await runEngram(cwd, env, ['init', '--global-branch', 'team']);
  assert.equal(migrated.code, 0, migrated.stderr);
  const config = JSON.parse(await readFile(path.join(workspaceMemoryRoot(cwd), 'engram.config.json'), 'utf8'));
  assert.equal(config.version, '0.0.4');
  assert.equal(config.scope, 'workspace');
  assert.deepEqual(config.roles, ['backend']);
  assert.equal(config.global_git.branch, 'team');
  assert.equal(config.live_sync.enabled, false);
  assert.equal(config.rule_variants.active, 'balanced');
  await rm(cwd, { recursive: true, force: true });
});

test('init migrates legacy workflow folders into skills and rebuilds index', async () => {
  const { cwd, env } = await tempWorkspace('engram-init-');
  await runEngram(cwd, env, ['init']);
  await mkdir(path.join(workspaceMemoryRoot(cwd), 'workflows'), { recursive: true });
  await writeFile(path.join(workspaceMemoryRoot(cwd), 'workflows', 'legacy-deploy.md'), legacySkill());
  const migrated = await runEngram(cwd, env, ['init']);
  assert.equal(migrated.code, 0, migrated.stderr);
  assert.match(migrated.stdout, /1 migrated/);
  await stat(path.join(workspaceMemoryRoot(cwd), 'skills', 'legacy-deploy.md'));
  await assert.rejects(stat(path.join(workspaceMemoryRoot(cwd), 'workflows')));
  const index = JSON.parse(await readFile(path.join(workspaceMemoryRoot(cwd), 'memory.index.json'), 'utf8'));
  assert.ok(index.entries.some((entry) => entry.file === 'skills/legacy-deploy.md'));
  await rm(cwd, { recursive: true, force: true });
});

test('init leaves colliding legacy files in place instead of overwriting', async () => {
  const { cwd, env } = await tempWorkspace('engram-init-');
  await runEngram(cwd, env, ['init']);
  await mkdir(path.join(workspaceMemoryRoot(cwd), 'workflows'), { recursive: true });
  await writeFile(path.join(workspaceMemoryRoot(cwd), 'workflows', 'same.md'), 'legacy copy\n');
  await writeFile(path.join(workspaceMemoryRoot(cwd), 'skills', 'same.md'), 'current copy\n');
  assert.equal((await runEngram(cwd, env, ['init'])).code, 0);
  assert.equal(await readFile(path.join(workspaceMemoryRoot(cwd), 'skills', 'same.md'), 'utf8'), 'current copy\n');
  assert.equal(await readFile(path.join(workspaceMemoryRoot(cwd), 'workflows', 'same.md'), 'utf8'), 'legacy copy\n');
  await rm(cwd, { recursive: true, force: true });
});

test('init repairs global scope scaffold without requiring a fresh workspace', async () => {
  const { cwd, env } = await tempWorkspace('engram-init-');
  await runEngram(cwd, env, ['init']);
  await rm(path.join(env.ENGRAM_GLOBAL_DIR, 'quarantine'), { recursive: true, force: true });
  await rm(path.join(env.ENGRAM_GLOBAL_DIR, 'HELP.md'), { force: true });
  const repaired = await runEngram(cwd, env, ['init']);
  assert.equal(repaired.code, 0, repaired.stderr);
  assert.match(repaired.stdout, /engram global reconciled/);
  await stat(path.join(env.ENGRAM_GLOBAL_DIR, 'quarantine'));
  assert.match(await readFile(path.join(env.ENGRAM_GLOBAL_DIR, 'HELP.md'), 'utf8'), /Engram Help/);
  await rm(cwd, { recursive: true, force: true });
});

test('init merges default ignore patterns and preserves audit files', async () => {
  const { cwd, env } = await tempWorkspace('engram-init-');
  await runEngram(cwd, env, ['init']);
  await writeFile(path.join(cwd, '.engramignore'), 'custom/**\nnode_modules/\n');
  await writeFile(path.join(workspaceMemoryRoot(cwd), 'changelog.md'), '# Engram Changelog\n\n- keep me\n');
  await writeFile(path.join(workspaceMemoryRoot(cwd), 'memory.hashes.json'), '{\n  "rules/a.md": "abc"\n}\n');
  const repaired = await runEngram(cwd, env, ['init']);
  assert.equal(repaired.code, 0, repaired.stderr);
  const ignore = await readFile(path.join(cwd, '.engramignore'), 'utf8');
  assert.match(ignore, /custom\/\*\*/);
  assert.match(ignore, /private\/\*\*/);
  assert.match(await readFile(path.join(workspaceMemoryRoot(cwd), 'changelog.md'), 'utf8'), /keep me/);
  assert.deepEqual(JSON.parse(await readFile(path.join(workspaceMemoryRoot(cwd), 'memory.hashes.json'), 'utf8')), { 'rules/a.md': 'abc' });
  await rm(cwd, { recursive: true, force: true });
});
