import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdir, readFile, readdir, rm, stat, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { VERSION } from '../dist/core/runtime/version.js';
import { runEngram, tempWorkspace, workspaceMemoryRoot } from './helpers.mjs';
import { parseFrontmatter } from '../dist/core/memory/frontmatter.js';
import { readTrace } from '../dist/core/traces/storage.js';

const GENERATED = '<!-- Generated by Engram skillset installer. Edit with care. -->';

function legacySkill() {
  return `---
id: legacy-deploy-flow
type: skill
scope: workspace
tags: [legacy, deploy]
author: test
confidence: high
---
# Legacy Deploy Flow

## Context

Old workspace used workflows directory.

## Content

- Run tests, build, then verify health.

## Example

engram load deploy
`;
}

test('init can run repeatedly and refresh generated skillset files', async () => {
  const { cwd, env } = await tempWorkspace('engram-init-');
  assert.equal((await runEngram(cwd, env, ['inject'])).code, 0);
  await writeFile(path.join(cwd, 'AGENTS.md'), `${GENERATED}\n\n# Old Engram Agent Skillset\n`);
  await writeFile(path.join(cwd, '.agents', 'skills', 'engram', 'SKILL.md'), `---
name: engram
description: Old generated Engram skill
---
# Engram Memory Management Skill

Engram = workspace memory.
`);
  const second = await runEngram(cwd, env, ['inject']);
  assert.equal(second.code, 0, second.stderr);
  assert.match(second.stdout, /✔ engram is injected!/);
  assert.match(await readFile(path.join(cwd, 'AGENTS.md'), 'utf8'), /<!-- engram:start -->/);
  assert.match(await readFile(path.join(cwd, '.agents', 'skills', 'engram', 'SKILL.md'), 'utf8'), /knowledge memory center/);
  assert.match(await readFile(path.join(cwd, '.agents', 'skills', 'engram', 'SKILL.md'), 'utf8'), /Session end/);
  assert.equal((await runEngram(cwd, env, ['inject'])).code, 0);
  await rm(cwd, { recursive: true, force: true });
});

test('init migrates legacy .engram root under .agents', async () => {
  const { cwd, env } = await tempWorkspace('engram-init-');
  await mkdir(path.join(cwd, '.engram', 'rules'), { recursive: true });
  await writeFile(path.join(cwd, '.engram', 'engram.config.json'), JSON.stringify({ version: '0.0.0', scope: 'workspace' }, null, 2));
  await writeFile(path.join(cwd, '.engram', 'rules', 'legacy-location.md'), legacySkill().replace('type: skill', 'type: rule'));
  const migrated = await runEngram(cwd, env, ['inject', '--no-skillset']);
  assert.equal(migrated.code, 0, migrated.stderr);
  assert.match(migrated.stdout, /✔ engram is injected!/);
  await stat(path.join(workspaceMemoryRoot(cwd), 'rules', 'legacy-location.md'));
  await assert.rejects(stat(path.join(cwd, '.engram')));
  await rm(cwd, { recursive: true, force: true });
});

test('init restores missing workspace scaffold files and directories', async () => {
  const { cwd, env } = await tempWorkspace('engram-init-');
  await runEngram(cwd, env, ['inject']);
  await rm(path.join(workspaceMemoryRoot(cwd), 'proposals'), { recursive: true, force: true });
  await rm(path.join(workspaceMemoryRoot(cwd), 'HELP.md'), { force: true });
  await rm(path.join(workspaceMemoryRoot(cwd), 'README.md'), { force: true });
  await rm(path.join(workspaceMemoryRoot(cwd), 'memory.index.json'), { force: true });
  await rm(path.join(workspaceMemoryRoot(cwd), 'memory.hashes.json'), { force: true });
  const repaired = await runEngram(cwd, env, ['inject']);
  assert.equal(repaired.code, 0, repaired.stderr);
  assert.match(repaired.stdout, /✔ engram is injected!/);
  await stat(path.join(workspaceMemoryRoot(cwd), 'proposals'));
  assert.match(await readFile(path.join(workspaceMemoryRoot(cwd), 'HELP.md'), 'utf8'), /--no-skillset/);
  assert.match(await readFile(path.join(workspaceMemoryRoot(cwd), 'README.md'), 'utf8'), /portable AI-agent memory/);
  assert.deepEqual(JSON.parse(await readFile(path.join(workspaceMemoryRoot(cwd), 'memory.hashes.json'), 'utf8')), {});
  await rm(cwd, { recursive: true, force: true });
});

test('init persists config migrations while preserving user settings', async () => {
  const { cwd, env } = await tempWorkspace('engram-init-');
  await runEngram(cwd, env, ['inject']);
  await writeFile(path.join(workspaceMemoryRoot(cwd), 'engram.config.json'), JSON.stringify({
    version: '0.0.0',
    scope: 'workspace',
    roles: ['backend'],
    global_git: { branch: 'legacy' }
  }, null, 2));
  const migrated = await runEngram(cwd, env, ['inject', '--global-branch', 'team']);
  assert.equal(migrated.code, 0, migrated.stderr);
  const config = JSON.parse(await readFile(path.join(workspaceMemoryRoot(cwd), 'engram.config.json'), 'utf8'));
  assert.equal(config.version, VERSION);
  assert.equal(config.scope, 'workspace');
  assert.deepEqual(config.roles, ['backend']);
  assert.equal(config.global_git.branch, 'team');
  assert.equal(config.live_sync.enabled, false);
  assert.equal(config.rule_variants.active, 'balanced');
  await rm(cwd, { recursive: true, force: true });
});

test('init migrates legacy workflow folders into skills and rebuilds index', async () => {
  const { cwd, env } = await tempWorkspace('engram-init-');
  await runEngram(cwd, env, ['inject']);
  await mkdir(path.join(workspaceMemoryRoot(cwd), 'workflows'), { recursive: true });
  await writeFile(path.join(workspaceMemoryRoot(cwd), 'workflows', 'legacy-deploy.md'), legacySkill());
  const migrated = await runEngram(cwd, env, ['inject']);
  assert.equal(migrated.code, 0, migrated.stderr);
  assert.match(migrated.stdout, /✔ engram is injected!/);
  await stat(path.join(workspaceMemoryRoot(cwd), 'skills', 'legacy-deploy.md'));
  await assert.rejects(stat(path.join(workspaceMemoryRoot(cwd), 'workflows')));
  const index = JSON.parse(await readFile(path.join(workspaceMemoryRoot(cwd), 'memory.index.json'), 'utf8'));
  assert.ok(index.entries.some((entry) => entry.file === 'skills/legacy-deploy.md'));
  await rm(cwd, { recursive: true, force: true });
});

test('init leaves colliding legacy files in place instead of overwriting', async () => {
  const { cwd, env } = await tempWorkspace('engram-init-');
  await runEngram(cwd, env, ['inject']);
  await mkdir(path.join(workspaceMemoryRoot(cwd), 'workflows'), { recursive: true });
  await writeFile(path.join(workspaceMemoryRoot(cwd), 'workflows', 'same.md'), 'legacy copy\n');
  await writeFile(path.join(workspaceMemoryRoot(cwd), 'skills', 'same.md'), 'current copy\n');
  assert.equal((await runEngram(cwd, env, ['inject'])).code, 0);
  assert.equal(await readFile(path.join(workspaceMemoryRoot(cwd), 'skills', 'same.md'), 'utf8'), 'current copy\n');
  assert.equal(await readFile(path.join(workspaceMemoryRoot(cwd), 'workflows', 'same.md'), 'utf8'), 'legacy copy\n');
  await rm(cwd, { recursive: true, force: true });
});

test('init repairs global scope scaffold without requiring a fresh workspace', async () => {
  const { cwd, env } = await tempWorkspace('engram-init-');
  await runEngram(cwd, env, ['inject']);
  await rm(path.join(env.ENGRAM_GLOBAL_DIR, 'quarantine'), { recursive: true, force: true });
  await rm(path.join(env.ENGRAM_GLOBAL_DIR, 'HELP.md'), { force: true });
  const repaired = await runEngram(cwd, env, ['inject']);
  assert.equal(repaired.code, 0, repaired.stderr);
  assert.match(repaired.stdout, /✔ engram is injected!/);
  await stat(path.join(env.ENGRAM_GLOBAL_DIR, 'quarantine'));
  assert.match(await readFile(path.join(env.ENGRAM_GLOBAL_DIR, 'HELP.md'), 'utf8'), /Engram Help/);
  await rm(cwd, { recursive: true, force: true });
});

test('init merges default ignore patterns and preserves audit files', async () => {
  const { cwd, env } = await tempWorkspace('engram-init-');
  await runEngram(cwd, env, ['inject']);
  await writeFile(path.join(cwd, '.engramignore'), 'custom/**\nnode_modules/\n');
  await writeFile(path.join(workspaceMemoryRoot(cwd), 'changelog.md'), '# Engram Changelog\n\n- keep me\n');
  await writeFile(path.join(workspaceMemoryRoot(cwd), 'memory.hashes.json'), '{\n  "rules/a.md": "abc"\n}\n');
  const repaired = await runEngram(cwd, env, ['inject']);
  assert.equal(repaired.code, 0, repaired.stderr);
  const ignore = await readFile(path.join(cwd, '.engramignore'), 'utf8');
  assert.match(ignore, /custom\/\*\*/);
  assert.match(ignore, /private\/\*\*/);
  assert.match(await readFile(path.join(workspaceMemoryRoot(cwd), 'changelog.md'), 'utf8'), /keep me/);
  assert.deepEqual(JSON.parse(await readFile(path.join(workspaceMemoryRoot(cwd), 'memory.hashes.json'), 'utf8')), { 'rules/a.md': 'abc' });
  await rm(cwd, { recursive: true, force: true });
});


test('init migrates legacy observation wrappers to traces exactly once', async () => {
  const { cwd, env } = await tempWorkspace('engram-observation-migrate-');
  const root = workspaceMemoryRoot(cwd);
  await mkdir(path.join(root, 'inbox'), { recursive: true });
  const observation = `---
source: observe
created: 2026-08-01T10:00:00.000Z
source_file: notes/session.txt
redacted_findings: 1
removed_injection_lines: 2
---

# Observation: Legacy fact

## Raw Note

Legacy durable fact.

## Next

Review before saving.
`;
  const file = path.join(root, 'inbox', 'legacy-observation.md');
  await writeFile(file, observation);
  const first = await runEngram(cwd, env, ['inject', '--no-skillset']);
  assert.equal(first.code, 0, first.stderr);
  const wrapper = parseFrontmatter(await readFile(file, 'utf8'));
  assert.match(wrapper.data.trace_id, /^tr_/);
  assert.equal(wrapper.data.authority, 'evidence');
  const trace = await readTrace(root, wrapper.data.trace_id);
  assert.equal(trace.text, 'Legacy durable fact.');
  assert.equal(trace.redactedFindings, 1);
  assert.equal(trace.removedInjectionLines, 2);
  const traceFilesBefore = await readdir(path.join(root, 'traces'));
  const second = await runEngram(cwd, env, ['inject', '--no-skillset']);
  assert.equal(second.code, 0, second.stderr);
  assert.deepEqual(await readdir(path.join(root, 'traces')), traceFilesBefore);
  await rm(cwd, { recursive: true, force: true });
});

test('legacy migration namespaces provenance by scope', async () => {
  const { cwd, env } = await tempWorkspace('engram-observation-scope-migrate-');
  const workspaceRoot = workspaceMemoryRoot(cwd);
  const globalRoot = env.ENGRAM_GLOBAL_DIR;
  const observation = `---
source: observe
created: 2026-08-01T10:00:00.000Z
---

# Observation

## Raw Note

Same legacy fact.
`;
  for (const root of [workspaceRoot, globalRoot]) {
    await mkdir(path.join(root, 'inbox'), { recursive: true });
    await writeFile(path.join(root, 'inbox', 'same.md'), observation);
  }
  const result = await runEngram(cwd, env, ['inject', '--no-skillset']);
  assert.equal(result.code, 0, result.stderr);
  const workspaceWrapper = parseFrontmatter(await readFile(path.join(workspaceRoot, 'inbox', 'same.md'), 'utf8'));
  const globalWrapper = parseFrontmatter(await readFile(path.join(globalRoot, 'inbox', 'same.md'), 'utf8'));
  assert.notEqual(workspaceWrapper.data.trace_id, globalWrapper.data.trace_id);
  assert.notEqual(workspaceWrapper.data.session_id, globalWrapper.data.session_id);
  assert.match(workspaceWrapper.data.session_id, /^legacy:workspace:/);
  assert.match(globalWrapper.data.session_id, /^legacy:global:/);
  await rm(cwd, { recursive: true, force: true });
});
