import test from 'node:test';
import assert from 'node:assert/strict';
import { rm, readFile, writeFile, mkdir } from 'node:fs/promises';
import path from 'node:path';
import { runEngram, tempWorkspace } from './helpers.mjs';
import {
  loadPanelData,
  apiConfigSet,
  apiConfigUpdate,
  apiConfigValidate,
  apiWorkspaceAdd,
  apiWorkspaceLink,
  apiWorkspaceRemove,
  apiProfileAdd,
  apiProfileActivate,
  apiProfileRemove,
  parseEntryText,
  apiAgentsScan,
  apiAgentLink,
  apiAgentUnlink,
  apiBrowseDirectories,
  apiMemoriesGraphData,
  apiResolveMemoryFile,
  apiArchiveMemory,
  apiAuthorState,
  apiAuthorSet,
  apiAuthorUnset,
  apiAuthorSyncPlan,
  apiAuthorMigrationPlan,
  apiUpgradePlan,
  apiUpgradeApply,
  apiUpgradeReview,
  apiUpgradeResolve,
  apiUpgradeResolveBatch,
  apiUpgradeOpenFile
} from '../dist/core/web/api.js';
import { scanUpgradeInventory } from '../dist/core/upgrade/inventory.js';
import { buildUpgradePlan } from '../dist/core/upgrade/planner.js';
import { loadConfig } from '../dist/core/runtime/config.js';
import { VERSION } from '../dist/core/runtime/constants.js';


async function hasSqlite() {
  const originalEmitWarning = process.emitWarning;
  process.emitWarning = function patchedEmitWarning(warning, ...args) {
    const message = typeof warning === 'string' ? warning : warning?.message ?? '';
    const option = args[0];
    const type = typeof option === 'string' ? option : option?.type ?? warning?.name ?? '';
    if (type === 'ExperimentalWarning' && message.includes('SQLite')) return false;
    return originalEmitWarning.call(this, warning, ...args);
  };
  try {
    try { await import('node:sqlite'); return true; } catch { /* check better-sqlite3 */ }
    try { await import('better-sqlite3'); return true; } catch { return false; }
  } finally {
    process.emitWarning = originalEmitWarning;
  }
}

function restoreEnv(name, value) {
  if (value === undefined) delete process.env[name];
  else process.env[name] = value;
}



test('web upgrade API uses the shared plan and rejects stale fingerprints', async () => {
  const { cwd, env } = await tempWorkspace('engram-web-upgrade-plan-');
  const old = { config: process.env.ENGRAM_CONFIG_DIR, global: process.env.ENGRAM_GLOBAL_DIR };
  process.env.ENGRAM_CONFIG_DIR = env.ENGRAM_CONFIG_DIR;
  process.env.ENGRAM_GLOBAL_DIR = env.ENGRAM_GLOBAL_DIR;
  try {
    const config = await loadConfig(cwd);
    const expected = buildUpgradePlan(await scanUpgradeInventory(cwd, config, VERSION), VERSION);
    const apiPlan = await apiUpgradePlan(cwd);
    assert.equal(apiPlan.fingerprint, expected.fingerprint);
    assert.deepEqual(apiPlan.items, expected.items);
    await assert.rejects(apiUpgradeApply(cwd, { fingerprint: apiPlan.fingerprint, confirmed: false }), /confirmation/i);
    await writeFile(path.join(cwd, 'AGENTS.md'), '<!-- Generated by Engram skillset installer. Edit with care. -->\n# stale\n');
    await assert.rejects(apiUpgradeApply(cwd, { fingerprint: apiPlan.fingerprint, confirmed: true }), /stale/i);
  } finally {
    restoreEnv('ENGRAM_CONFIG_DIR', old.config);
    restoreEnv('ENGRAM_GLOBAL_DIR', old.global);
    await rm(cwd, { recursive: true, force: true });
  }
});
test('web api connects and disconnects OpenCode hooks', async () => {
  const { cwd, env } = await tempWorkspace('engram-web-opencode-');
  const previous = {
    agentHome: process.env.ENGRAM_AGENT_HOME,
    configHome: process.env.ENGRAM_AGENT_CONFIG_HOME,
    configDir: process.env.ENGRAM_CONFIG_DIR,
    globalDir: process.env.ENGRAM_GLOBAL_DIR
  };
  const agentHome = path.join(cwd, 'agent-home');
  const configHome = path.join(cwd, 'agent-config');
  try {
    process.env.ENGRAM_AGENT_HOME = agentHome;
    process.env.ENGRAM_AGENT_CONFIG_HOME = configHome;
    process.env.ENGRAM_CONFIG_DIR = env.ENGRAM_CONFIG_DIR;
    process.env.ENGRAM_GLOBAL_DIR = env.ENGRAM_GLOBAL_DIR;
    assert.match(await apiAgentLink(cwd, 'opencode', true), /Connected opencode globally/);
    const pluginFile = path.join(agentHome, '.config', 'opencode', 'plugins', 'engram.js');
    assert.match(await readFile(pluginFile, 'utf8'), /EngramOpenCodePlugin/);
    assert.match(await apiAgentUnlink(cwd, 'opencode', true), /Disconnected opencode globally/);
    await assert.rejects(readFile(pluginFile, 'utf8'));
  } finally {
    restoreEnv('ENGRAM_AGENT_HOME', previous.agentHome);
    restoreEnv('ENGRAM_AGENT_CONFIG_HOME', previous.configHome);
    restoreEnv('ENGRAM_CONFIG_DIR', previous.configDir);
    restoreEnv('ENGRAM_GLOBAL_DIR', previous.globalDir);
    await rm(cwd, { recursive: true, force: true });
  }
});
test('web UI api workspace, profile, config handlers and entry text parser', async () => {
  const { cwd, env } = await tempWorkspace('engram-web-api-');

  // Set up the environment variables for config dir and global dir so the API calls resolve correctly.
  const oldEnv = {
    ENGRAM_CONFIG_DIR: process.env.ENGRAM_CONFIG_DIR,
    ENGRAM_GLOBAL_DIR: process.env.ENGRAM_GLOBAL_DIR,
    NODE_ENV: process.env.NODE_ENV
  };
  process.env.ENGRAM_CONFIG_DIR = env.ENGRAM_CONFIG_DIR;
  process.env.ENGRAM_GLOBAL_DIR = env.ENGRAM_GLOBAL_DIR;
  process.env.NODE_ENV = 'test';

  try {
    // 1. parseEntryText
    const entryText = `
## Runtime
- not this

## Core Configurations
- scope: workspace
- proof: off
`;
    const parsed = parseEntryText(entryText);
    assert.equal(parsed.length, 1);
    assert.equal(parsed[0].group, 'Core Configurations');
    assert.deepEqual(parsed[0].rows, [['scope', 'workspace'], ['proof', 'off']]);

    // 2. loadPanelData on empty/uninitialized workspace
    const initialData = await loadPanelData(cwd, entryText);
    assert.equal(initialData.sqliteAvailable, await hasSqlite());
    assert.equal(initialData.isInitialized, false);
    assert.equal(initialData.cwd, cwd);

    const oldLatest = process.env.ENGRAM_LATEST_VERSION;
    process.env.ENGRAM_LATEST_VERSION = '999.0.0';
    const updateData = await loadPanelData(cwd, entryText);
    if (oldLatest === undefined) delete process.env.ENGRAM_LATEST_VERSION;
    else process.env.ENGRAM_LATEST_VERSION = oldLatest;
    assert.equal(updateData.latestVersion, '999.0.0');

    // 3. apiConfigSet (valid keys)
    const setScope = await apiConfigSet('scope', 'global', cwd);
    assert.match(setScope, /Set scope = global/);

    const setRead = await apiConfigSet('read', 'always', cwd);
    assert.match(setRead, /Set read = always/);

    const setProof = await apiConfigSet('proof', 'compact', cwd);
    assert.match(setProof, /Set proof = compact/);

    const validation = apiConfigValidate({
      'load.limit': '12',
      'graph.min_related_score': '0.4',
      roles: 'agent, reviewer'
    });
    assert.equal(validation.ok, true);
    assert.deepEqual(validation.riskyKeys, []);

    const batchSet = await apiConfigUpdate({
      'load.limit': '12',
      'graph.min_related_score': '0.4',
      roles: 'agent, reviewer'
    }, cwd);
    assert.match(batchSet, /Saved 3 config settings/);

    await assert.rejects(
      async () => {
        await apiConfigUpdate({ read: 'always', 'load.limit': '99' }, cwd);
      },
      /load\.limit must be at most 32/
    );

    // 4. apiConfigSet (invalid key)
    await assert.rejects(
      async () => {
        await apiConfigSet('invalid_key', 'value', cwd);
      },
      /Unknown config key/
    );

    // 5. Workspace operations (require SQLite — skip when unavailable)
    const sqliteOk = await hasSqlite();
    if (sqliteOk) {
      const wsPath = path.join(cwd, 'another-workspace');
      const wsAdd = await apiWorkspaceAdd(wsPath, 'another');
      assert.match(wsAdd, /Registered/);

      const wsLink = await apiWorkspaceLink(wsPath, true);
      assert.match(wsLink, /Linked/);

      const wsUnlink = await apiWorkspaceLink(wsPath, false);
      assert.match(wsUnlink, /Unlinked/);

      const wsRemove = await apiWorkspaceRemove(wsPath);
      assert.match(wsRemove, /Removed/);

      // 6. Profile operations (also require SQLite)
      const profilePath = path.join(cwd, 'another-profile');
      const profileAdd = await apiProfileAdd('another', profilePath, 'global');
      assert.match(profileAdd, /Profile saved/);

      const profileActivate = await apiProfileActivate('another');
      assert.match(profileActivate, /Active profile/);

      const profileRemove = await apiProfileRemove('another');
      assert.match(profileRemove, /Profile deleted/);
    }

    // 7. Verify config values after set
    const finalData = await loadPanelData(cwd, entryText);
    assert.equal(finalData.config.scope, 'global');
    assert.equal(finalData.config.read, 'always');
    assert.equal(finalData.config.proof, 'compact');
    assert.equal(finalData.config.load.limit, 12);
    assert.equal(finalData.config.graph.min_related_score, 0.4);
    assert.deepEqual(finalData.config.roles, ['agent', 'reviewer']);

    // 8. Fallback: apiConfigSet persists JSON even when SQLite is unavailable
    const schema = await import('../dist/core/config-db/schema.js');
    schema.setConfigDbUnavailableForTests(true);
    try {
      const fallbackSet = await apiConfigSet('read', 'manual', cwd);
      assert.match(fallbackSet, /Set read = manual/);
      assert.match(fallbackSet, /SQLite unavailable; JSON only/);

      const fallbackData = await loadPanelData(cwd, entryText);
      assert.equal(fallbackData.sqliteAvailable, false);
      assert.equal(fallbackData.config.read, 'manual');
    } finally {
      schema.setConfigDbUnavailableForTests(false);
    }

    // 9. Final config verification reflects last saved values
    const finalData2 = await loadPanelData(cwd, entryText);
    assert.equal(finalData2.config.scope, 'global');
    // After SQLite is available again, DB value 'always' takes priority over JSON fallback 'manual'
    assert.equal(finalData2.config.read, sqliteOk ? 'always' : 'manual');
    assert.equal(finalData2.config.proof, 'compact');

    // 10. Agent Connection APIs
    const agents = await apiAgentsScan(cwd);
    assert.ok(Array.isArray(agents));
    // Verify structure
    const claudeAgent = agents.find((a) => a.id === 'claude');
    assert.ok(claudeAgent);
    assert.equal(claudeAgent.name, 'Anthropic Claude');
    assert.equal(claudeAgent.workspaceLinked, false);

    // Since default scope in test is 'global' (from previous setScope test step),
    // linking workspace should skip first.
    const linkResultGlobal = await apiAgentLink(cwd, 'claude', false);
    assert.match(linkResultGlobal, /Skipped claude \(workspace\): config scope is global/);

    // Set scope back to 'both'
    await apiConfigSet('scope', 'both', cwd);

    // Link workspace
    const linkResult = await apiAgentLink(cwd, 'claude', false);
    assert.match(linkResult, /Connected claude in this workspace/);

    // Verify it is now linked in workspace
    const agentsAfterLink = await apiAgentsScan(cwd);
    const claudeAgentAfter = agentsAfterLink.find((a) => a.id === 'claude');
    assert.equal(claudeAgentAfter.workspaceLinked, true);

    // Unlink workspace
    const unlinkResult = await apiAgentUnlink(cwd, 'claude', false);
    assert.match(unlinkResult, /Disconnected claude from this workspace/);

    // Verify it is unlinked
    const agentsAfterUnlink = await apiAgentsScan(cwd);
    const claudeAgentAfterUnlink = agentsAfterUnlink.find((a) => a.id === 'claude');
    assert.equal(claudeAgentAfterUnlink.workspaceLinked, false);

    // Test that when config scope is global, workspace linking is skipped even if initialized
    await apiConfigSet('scope', 'global', cwd);
    const linkGlobalScopeResult = await apiAgentLink(cwd, 'claude', false);
    assert.match(linkGlobalScopeResult, /Skipped claude \(workspace\): config scope is global/);

    // Link global
    const linkGlobalResult = await apiAgentLink(cwd, 'claude', true);
    assert.match(linkGlobalResult, /Connected claude globally/);

    // Verify linked globally
    const agentsAfterGlobalLink = await apiAgentsScan(cwd);
    const claudeAgentAfterGlobal = agentsAfterGlobalLink.find((a) => a.id === 'claude');
    assert.equal(claudeAgentAfterGlobal.globalLinked, true);

    // Unlink global
    const unlinkGlobalResult = await apiAgentUnlink(cwd, 'claude', true);
    assert.match(unlinkGlobalResult, /Disconnected claude globally/);

    // Verify unlinked globally
    const agentsAfterGlobalUnlink = await apiAgentsScan(cwd);
    const claudeAgentAfterGlobalUnlink = agentsAfterGlobalUnlink.find((a) => a.id === 'claude');
    assert.equal(claudeAgentAfterGlobalUnlink.globalLinked, false);
  } finally {
    // Restore environment
    process.env.ENGRAM_CONFIG_DIR = oldEnv.ENGRAM_CONFIG_DIR;
    process.env.ENGRAM_GLOBAL_DIR = oldEnv.ENGRAM_GLOBAL_DIR;
    process.env.NODE_ENV = oldEnv.NODE_ENV;
    await rm(cwd, { recursive: true, force: true });
  }
});

test('web UI api core data reports duplicate memory candidates and scope metadata', async () => {
  const { cwd, env } = await tempWorkspace('engram-web-core-');
  const oldEnv = {
    ENGRAM_CONFIG_DIR: process.env.ENGRAM_CONFIG_DIR,
    ENGRAM_GLOBAL_DIR: process.env.ENGRAM_GLOBAL_DIR,
    NODE_ENV: process.env.NODE_ENV
  };
  process.env.ENGRAM_CONFIG_DIR = env.ENGRAM_CONFIG_DIR;
  process.env.ENGRAM_GLOBAL_DIR = env.ENGRAM_GLOBAL_DIR;
  process.env.NODE_ENV = 'test';

  try {
    const { runEngram, workspaceMemoryRoot } = await import('./helpers.mjs');
    const { mkdir, writeFile } = await import('node:fs/promises');
    const path = await import('node:path');
    const { apiCoreData, apiGetMemoryContent } = await import('../dist/core/web/api.js');

    await runEngram(cwd, env, ['inject', '--no-skillset']);
    const rules = path.join(workspaceMemoryRoot(cwd), 'rules');
    await mkdir(rules, { recursive: true });
    const memory = ({ id, title, content }) => `---
id: ${id}
type: rule
scope: workspace
tags: [pnpm, scripts]
created: 2026-06-01
updated: 2026-06-01
author: dev@example.com
source: manual
confidence: high
---
# ${title}

## Context

Dashboard duplicate test.

## Content

- ${content}

## Example

pnpm test
`;
    await writeFile(path.join(rules, 'prefer-pnpm-package-scripts.md'), memory({
      id: 'prefer-pnpm-package-scripts',
      title: 'Prefer pnpm package scripts',
      content: 'Prefer pnpm package scripts for workspace tasks.'
    }));
    await writeFile(path.join(rules, 'run-pnpm-for-npm-scripts.md'), memory({
      id: 'run-pnpm-for-npm-scripts',
      title: 'Run pnpm for npm scripts',
      content: 'Use pnpm when running npm scripts in the workspace.'
    }));
    await runEngram(cwd, env, ['rebuild-index']);

    const data = await apiCoreData(cwd, { semantic: true, rebuild: false, scope: 'all' });
    assert.equal(data.scope.activeProfile === undefined || typeof data.scope.activeProfile === 'string', true);
    assert.ok(Array.isArray(data.duplicates));
    assert.ok(data.duplicates.some((pair) => pair.a.file.includes('prefer-pnpm-package-scripts.md') && pair.b.file.includes('run-pnpm-for-npm-scripts.md')));
    assert.ok(data.prompts.resolveDuplicates.includes('UPDATE:'));
    assert.ok(data.prompts.metacognize.includes('engram metacognize'));
    assert.ok(data.relationship.nodes.length >= 3);
    assert.ok(data.relationship.links.some((link) => link.kind === 'duplicate'));

    const content = await apiGetMemoryContent(cwd, data.scope.activeProfile, 'workspace', 'rules/prefer-pnpm-package-scripts.md');
    assert.ok(content.includes('Prefer pnpm package scripts'));
    await assert.rejects(
      () => apiGetMemoryContent(cwd, data.scope.activeProfile, 'workspace', path.join('..', 'package.json')),
      /Path escapes allowed root/
    );

    const loadResult = await runEngram(cwd, env, ['load', '--id', 'prefer-pnpm-package-scripts']);
    assert.equal(loadResult.code, 0, loadResult.stderr);
    assert.match(loadResult.stdout, /prefer-pnpm-package-scripts/);

    // 9. apiBrowseDirectories
    const browseRes = await apiBrowseDirectories(cwd, cwd);
    assert.equal(browseRes.ok, true);
    assert.equal(typeof browseRes.currentPath, 'string');
    assert.ok(Array.isArray(browseRes.directories));
    assert.ok(Array.isArray(browseRes.drives));
    for (const entry of browseRes.directories) {
      assert.equal(typeof entry.name, 'string');
      assert.equal(typeof entry.path, 'string');
      assert.ok(path.isAbsolute(entry.path));
    }

    const missingBrowse = await apiBrowseDirectories(path.join(cwd, 'missing-folder'), cwd);
    assert.equal(missingBrowse.ok, false);
    assert.match(missingBrowse.error, /Cannot access directory/);
    assert.deepEqual(missingBrowse.directories, []);
  } finally {
    process.env.ENGRAM_CONFIG_DIR = oldEnv.ENGRAM_CONFIG_DIR;
    process.env.ENGRAM_GLOBAL_DIR = oldEnv.ENGRAM_GLOBAL_DIR;
    process.env.NODE_ENV = oldEnv.NODE_ENV;
    await rm(cwd, { recursive: true, force: true });
  }
});

test('web UI api memories graph reports scopes, dependency links, and thin duplicate links', async () => {
  const { cwd, env } = await tempWorkspace('engram-web-memories-');
  const oldEnv = {
    ENGRAM_CONFIG_DIR: process.env.ENGRAM_CONFIG_DIR,
    ENGRAM_GLOBAL_DIR: process.env.ENGRAM_GLOBAL_DIR,
    NODE_ENV: process.env.NODE_ENV
  };
  process.env.ENGRAM_CONFIG_DIR = env.ENGRAM_CONFIG_DIR;
  process.env.ENGRAM_GLOBAL_DIR = env.ENGRAM_GLOBAL_DIR;
  process.env.NODE_ENV = 'test';

  try {
    const { runEngram, workspaceMemoryRoot } = await import('./helpers.mjs');
    const { mkdir, writeFile } = await import('node:fs/promises');
    const path = await import('node:path');

    await runEngram(cwd, env, ['inject', '--no-skillset']);
    const rules = path.join(workspaceMemoryRoot(cwd), 'rules');
    await mkdir(rules, { recursive: true });

    const memory = ({ id, title, content, dependsOn = [], evidenceRefs = [], derivedFrom = [], revision = 1, supersedes = [], supersededBy = '', validFrom = '2026-06-01', validUntil = '', lastConfirmed = '2026-06-01' }) => `---
schema_version: 3
id: ${id}
type: rule
scope: workspace
authority: instruction
tags: [graph, ui]
depends_on: [${dependsOn.join(', ')}]
evidence_refs: [${evidenceRefs.join(', ')}]
derived_from: [${derivedFrom.join(', ')}]
revision: ${revision}
supersedes: [${supersedes.join(', ')}]
superseded_by: ${supersededBy}
valid_from: ${validFrom}
valid_until: ${validUntil}
last_confirmed: ${lastConfirmed}
created: 2026-06-01
updated: 2026-06-01
author: dev@example.com
source: manual
confidence: high
---
# ${title}

## Context

Memories graph test.

## Content

- ${content}

## Example

engram load graph
`;

    await writeFile(path.join(rules, 'base-memory.md'), memory({
      id: 'base-memory',
      title: 'Base memory',
      content: 'Use the base memory before dependent graph memories. base-only-search-phrase',
      evidenceRefs: ['tr_web_evidence_1'],
      derivedFrom: ['session-web-1'],
      revision: 3,
      supersedes: ['older-base-memory'],
      supersededBy: 'newer-base-memory',
      validFrom: '2026-06-01',
      validUntil: '2027-06-01',
      lastConfirmed: '2026-08-05'
    }));
    await writeFile(path.join(rules, 'dependent-memory.md'), memory({
      id: 'dependent-memory',
      title: 'Dependent memory',
      content: 'Use the dependent graph memory after the base memory.',
      dependsOn: ['base-memory']
    }));
    await writeFile(path.join(rules, 'similar-dependent-memory.md'), memory({
      id: 'similar-dependent-memory',
      title: 'Similar dependent memory',
      content: 'Use dependent graph memories after base graph memories.'
    }));

    await runEngram(cwd, env, ['rebuild-index']);

    const data = await apiMemoriesGraphData(cwd, {
      scopes: ['workspace'],
      semantic: true,
      rebuild: false,
      limit: 50
    });

    assert.deepEqual(data.filters.enabledScopes, ['workspace']);
    assert.ok(data.nodes.some((node) => node.memoryId === 'base-memory'));
    assert.ok(data.nodes.some((node) => node.memoryId === 'dependent-memory'));
    const baseNode = data.nodes.find((node) => node.memoryId === 'base-memory');
    assert.equal(baseNode.authority, 'instruction');
    assert.deepEqual(baseNode.evidenceRefs, ['tr_web_evidence_1']);
    assert.deepEqual(baseNode.derivedFrom, ['session-web-1']);
    assert.equal(baseNode.revision, 3);
    assert.deepEqual(baseNode.supersedes, ['older-base-memory']);
    assert.equal(baseNode.supersededBy, 'newer-base-memory');
    assert.equal(baseNode.validFrom, '2026-06-01');
    assert.equal(baseNode.validUntil, '2027-06-01');
    assert.equal(baseNode.lastConfirmed, '2026-08-05');
    assert.ok(data.links.some((link) => link.kind === 'dependency' && link.thin === false));
    assert.ok(data.links.some((link) => (link.kind === 'duplicate' || link.kind === 'semantic') && link.thin === true));
    assert.ok(data.stats.workspace >= 3);
    assert.equal(data.stats.total, data.nodes.length);

    const workspaceOnly = await apiMemoriesGraphData(cwd, {
      scopes: ['workspace'],
      semantic: false,
      rebuild: false,
      limit: 50
    });
    assert.equal(workspaceOnly.nodes.every((node) => node.sourceScope === 'workspace'), true);

    const directSearch = await apiMemoriesGraphData(cwd, {
      scopes: ['workspace'],
      semantic: true,
      search: 'base-only-search-phrase',
      searchMode: 'direct',
      rebuild: false,
      limit: 50
    });
    assert.deepEqual(directSearch.nodes.map((node) => node.memoryId), ['base-memory']);

    const relatedSearch = await apiMemoriesGraphData(cwd, {
      scopes: ['workspace'],
      semantic: true,
      search: 'base-only-search-phrase',
      searchMode: 'related',
      rebuild: false,
      limit: 50
    });
    assert.ok(relatedSearch.nodes.some((node) => node.memoryId === 'base-memory'));
    assert.ok(relatedSearch.nodes.some((node) => node.memoryId === 'dependent-memory'));
    assert.ok(relatedSearch.links.every((link) => relatedSearch.nodes.some((node) => node.id === link.from) && relatedSearch.nodes.some((node) => node.id === link.to)));
  } finally {
    process.env.ENGRAM_CONFIG_DIR = oldEnv.ENGRAM_CONFIG_DIR;
    process.env.ENGRAM_GLOBAL_DIR = oldEnv.ENGRAM_GLOBAL_DIR;
    process.env.NODE_ENV = oldEnv.NODE_ENV;
    await rm(cwd, { recursive: true, force: true });
  }
});

test('web UI memories api resolves edit target and archives memory on delete action', async () => {
  const { cwd, env } = await tempWorkspace('engram-web-memory-actions-');
  const oldEnv = {
    ENGRAM_CONFIG_DIR: process.env.ENGRAM_CONFIG_DIR,
    ENGRAM_GLOBAL_DIR: process.env.ENGRAM_GLOBAL_DIR,
    NODE_ENV: process.env.NODE_ENV
  };
  process.env.ENGRAM_CONFIG_DIR = env.ENGRAM_CONFIG_DIR;
  process.env.ENGRAM_GLOBAL_DIR = env.ENGRAM_GLOBAL_DIR;
  process.env.NODE_ENV = 'test';

  try {
    const { runEngram, workspaceMemoryRoot } = await import('./helpers.mjs');
    const { mkdir, readFile, stat, writeFile } = await import('node:fs/promises');
    const path = await import('node:path');

    await runEngram(cwd, env, ['inject', '--no-skillset']);
    const rules = path.join(workspaceMemoryRoot(cwd), 'rules');
    await mkdir(rules, { recursive: true });
    await writeFile(path.join(rules, 'archive-me.md'), `---
id: archive-me
type: rule
scope: workspace
tags: [graph]
created: 2026-06-01
updated: 2026-06-01
author: dev@example.com
source: manual
confidence: high
---
# Archive me

## Context

Action test.

## Content

- Archive through Memories graph.

## Example

engram archive archive-me
`);
    await runEngram(cwd, env, ['rebuild-index']);

    const resolved = await apiResolveMemoryFile(cwd, 'default', 'workspace', 'rules/archive-me.md');
    assert.equal(resolved.file, 'rules/archive-me.md');
    assert.match(resolved.path, /archive-me\.md$/);
    assert.match(resolved.editorUrl, /^vscode:\/\/file\//);

    const archived = await apiArchiveMemory(cwd, {
      profile: 'default',
      scope: 'workspace',
      file: 'rules/archive-me.md',
      id: 'archive-me',
      reason: 'Deleted from Memories graph view'
    });
    assert.match(archived.message, /Archived ->/);
    assert.equal(archived.archived, true);

    await assert.rejects(
      () => stat(path.join(rules, 'archive-me.md')),
      /ENOENT/
    );
    const archivedText = await readFile(archived.path, 'utf8');
    assert.match(archivedText, /Deleted from Memories graph view/);
  } finally {
    process.env.ENGRAM_CONFIG_DIR = oldEnv.ENGRAM_CONFIG_DIR;
    process.env.ENGRAM_GLOBAL_DIR = oldEnv.ENGRAM_GLOBAL_DIR;
    process.env.NODE_ENV = oldEnv.NODE_ENV;
    await rm(cwd, { recursive: true, force: true });
  }
});




test('web API author functions share core validation, resolution, and confirmation gates', async () => {
  const { cwd, env } = await tempWorkspace('engram-web-author-api-');
  const previous = {
    config: process.env.ENGRAM_CONFIG_DIR,
    global: process.env.ENGRAM_GLOBAL_DIR
  };
  process.env.ENGRAM_CONFIG_DIR = env.ENGRAM_CONFIG_DIR;
  process.env.ENGRAM_GLOBAL_DIR = env.ENGRAM_GLOBAL_DIR;
  try {
    const initial = await apiAuthorState(cwd);
    assert.equal(initial.resolved.source, 'unresolved');
    await assert.rejects(apiAuthorSet(cwd, { scope: 'global', name: 'Jane Doe', email: 'jane@example.com', confirmed: false }), /confirmation/i);
    const saved = await apiAuthorSet(cwd, { scope: 'global', name: 'Jane Doe', email: 'jane@example.com', confirmed: true });
    assert.equal(saved.current.email, 'jane@example.com');
    const state = await apiAuthorState(cwd);
    assert.equal(state.resolved.source, 'global');
    assert.equal((await apiAuthorSyncPlan(cwd)).next.name, 'Jane Doe');
    assert.equal((await apiAuthorMigrationPlan(cwd, 'both')).scope, 'both');
    await assert.rejects(apiAuthorUnset(cwd, { scope: 'global', confirmed: false }), /confirmation/i);
    const removed = await apiAuthorUnset(cwd, { scope: 'global', confirmed: true });
    assert.equal(removed.current, null);
    const panel = await loadPanelData(cwd, '');
    assert.ok(panel.author);
  } finally {
    if (previous.config === undefined) delete process.env.ENGRAM_CONFIG_DIR; else process.env.ENGRAM_CONFIG_DIR = previous.config;
    if (previous.global === undefined) delete process.env.ENGRAM_GLOBAL_DIR; else process.env.ENGRAM_GLOBAL_DIR = previous.global;
    await rm(cwd, { recursive: true, force: true });
  }
});


test('web upgrade review API exposes proposals, persists decisions, and gates final apply', async () => {
  const { cwd, env } = await tempWorkspace('engram-web-upgrade-review-');
  const old = { config: process.env.ENGRAM_CONFIG_DIR, global: process.env.ENGRAM_GLOBAL_DIR };
  process.env.ENGRAM_CONFIG_DIR = env.ENGRAM_CONFIG_DIR;
  process.env.ENGRAM_GLOBAL_DIR = env.ENGRAM_GLOBAL_DIR;
  try {
    await mkdir(path.join(cwd, '.agents'), { recursive: true });
    await writeFile(path.join(cwd, 'AGENTS.md'), '# Human\n\n<!-- engram:start -->\nOLD\n<!-- engram:end -->\n');
    await writeFile(path.join(cwd, '.agents', 'engram.md'), '# Human-owned custom guide\n');
    let plan = await apiUpgradePlan(cwd);
    const conflict = plan.items.find((item) => item.kind === 'skillset' && item.status === 'conflict');
    assert.ok(conflict, JSON.stringify(plan.items, null, 2));
    assert.equal(plan.review?.pendingReviewCount, 1);
    await assert.rejects(apiUpgradeApply(cwd, { fingerprint: plan.fingerprint, confirmed: true }), /requires review/i);

    const review = await apiUpgradeReview(cwd, plan.fingerprint, conflict.id);
    assert.equal(review.proposal.current, '# Human-owned custom guide\n');
    assert.notEqual(review.proposal.proposed, review.proposal.current);
    assert.equal(review.saved.state, 'pending');
    assert.equal(review.proposal.replaceable, false);
    assert.equal(review.proposal.ownership, 'unknown');
    assert.equal(review.proposal.forceMode, 'none');
    assert.equal(review.proposal.forceWarning, undefined);

    const resolved = await apiUpgradeResolve(cwd, {
      fingerprint: plan.fingerprint,
      itemId: conflict.id,
      state: 'keep-current'
    });
    assert.equal(resolved.review.pendingReviewCount, 0);
    assert.equal(resolved.saved.state, 'keep-current');

    plan = await apiUpgradePlan(cwd);
    assert.equal(plan.review?.pendingReviewCount, 0, JSON.stringify(plan.items.filter((item) => item.status === 'conflict' || item.status === 'invalid'), null, 2));
    const result = await apiUpgradeApply(cwd, { fingerprint: plan.fingerprint, confirmed: true });
    assert.equal(result.conflicts.length, 1);
    assert.equal(await readFile(path.join(cwd, '.agents', 'engram.md'), 'utf8'), '# Human-owned custom guide\n');
    const converged = await apiUpgradePlan(cwd);
    const instructionRow = converged.items.find((item) => path.resolve(item.file) === path.resolve(path.join(cwd, 'AGENTS.md')));
    assert.ok(instructionRow);
    assert.equal(instructionRow.status, 'current');
    const guideRow = converged.items.find((item) => path.resolve(item.file) === path.resolve(path.join(cwd, '.agents', 'engram.md')));
    assert.ok(guideRow);
    assert.equal(guideRow.status, 'conflict');
  } finally {
    restoreEnv('ENGRAM_CONFIG_DIR', old.config);
    restoreEnv('ENGRAM_GLOBAL_DIR', old.global);
    await rm(cwd, { recursive: true, force: true });
  }
});



test('global shared guide plus managed instruction converge in one upgrade pass across codex claude and gemini', async () => {
  const { cwd, env } = await tempWorkspace('engram-web-global-upgrade-converge-');
  const agentHome = path.join(cwd, 'agent-home');
  const agentConfigHome = path.join(cwd, 'agent-config');
  const globalEnv = { ...env, ENGRAM_AGENT_HOME: agentHome, ENGRAM_AGENT_CONFIG_HOME: agentConfigHome };
  const old = {
    config: process.env.ENGRAM_CONFIG_DIR,
    global: process.env.ENGRAM_GLOBAL_DIR,
    agentHome: process.env.ENGRAM_AGENT_HOME,
    agentConfigHome: process.env.ENGRAM_AGENT_CONFIG_HOME
  };
  process.env.ENGRAM_CONFIG_DIR = globalEnv.ENGRAM_CONFIG_DIR;
  process.env.ENGRAM_GLOBAL_DIR = globalEnv.ENGRAM_GLOBAL_DIR;
  process.env.ENGRAM_AGENT_HOME = agentHome;
  process.env.ENGRAM_AGENT_CONFIG_HOME = agentConfigHome;
  try {
    for (const target of ['codex', 'claude', 'gemini']) {
      const linked = await runEngram(cwd, globalEnv, ['link', '--global', target]);
      assert.equal(linked.code, 0, linked.stderr);
    }

    const guideFile = path.join(agentHome, '.agents', 'engram.md');
    const instructionFile = path.join(agentHome, '.codex', 'AGENTS.md');
    await writeFile(guideFile, '# User manually edited shared guide\n');
    const instruction = await readFile(instructionFile, 'utf8');
    assert.match(instruction, /Engram memory may arrive through hooks and MCP\./);
    await writeFile(instructionFile, instruction.replace('Engram memory may arrive through hooks and MCP.', 'OLD MANUAL CONTENT INSIDE ENGRAM BLOCK'));

    let plan = await apiUpgradePlan(cwd);
    const sharedRows = plan.items.filter((item) => path.resolve(item.file) === path.resolve(guideFile));
    assert.equal(sharedRows.length, 1, JSON.stringify(sharedRows, null, 2));
    const shared = sharedRows[0];
    assert.equal(shared.status, 'conflict');
    assert.equal(shared.forceMode, 'replace-file');
    assert.deepEqual(shared.agents, ['claude', 'codex', 'gemini']);
    const instructionRow = plan.items.find((item) => path.resolve(item.file) === path.resolve(instructionFile));
    assert.equal(instructionRow?.status, 'outdated');

    await apiUpgradeResolve(cwd, { fingerprint: plan.fingerprint, itemId: shared.id, state: 'force-latest' });
    plan = await apiUpgradePlan(cwd);
    assert.equal(plan.review?.pendingReviewCount, 0);
    const result = await apiUpgradeApply(cwd, { fingerprint: plan.fingerprint, confirmed: true });
    assert.equal(result.conflicts.length, 0);
    const guideBackup = `${guideFile}.engram-upgrade-0.0.28.bak`;
    assert.equal(await readFile(guideBackup, 'utf8'), '# User manually edited shared guide\n');

    const after = await apiUpgradePlan(cwd);
    for (const file of [guideFile, instructionFile]) {
      const item = after.items.find((row) => path.resolve(row.file) === path.resolve(file));
      assert.ok(item, `post-upgrade inventory missing ${file}`);
      assert.equal(item.status, 'current', `${file} remained ${item.status}: ${item.reason}`);
    }
    assert.equal(after.items.filter((item) => path.resolve(item.file) === path.resolve(guideFile)).length, 1);
  } finally {
    restoreEnv('ENGRAM_CONFIG_DIR', old.config);
    restoreEnv('ENGRAM_GLOBAL_DIR', old.global);
    restoreEnv('ENGRAM_AGENT_HOME', old.agentHome);
    restoreEnv('ENGRAM_AGENT_CONFIG_HOME', old.agentConfigHome);
    await rm(cwd, { recursive: true, force: true });
  }
});

async function batchUpgradeFixture(prefix) {
  const { cwd, env } = await tempWorkspace(prefix);
  const agentHome = path.join(cwd, 'agent-home');
  const globalEnv = {
    ...env,
    ENGRAM_AGENT_HOME: agentHome,
    ENGRAM_AGENT_CONFIG_HOME: path.join(cwd, 'agent-config')
  };
  const linked = await runEngram(cwd, globalEnv, ['link', '--global', 'codex']);
  assert.equal(linked.code, 0, linked.stderr);
  await writeFile(path.join(agentHome, '.agents', 'engram.md'), '# Registered global guide edited by user\n');
  await mkdir(path.join(cwd, '.agents', '.engram', 'knowledge'), { recursive: true });
  await writeFile(path.join(cwd, '.agents', '.engram', 'knowledge', 'invalid.md'), `---
id: invalid
type: knowledge
scope: workspace
---
# Invalid
`);
  await writeFile(path.join(cwd, 'AGENTS.md'), '# Human\n\n<!-- engram:start -->\nOLD\n<!-- engram:end -->\n');
  await writeFile(path.join(cwd, '.agents', 'engram.md'), '# Human workspace guide\n');
  await mkdir(path.join(cwd, '.cursor', 'rules'), { recursive: true });
  await writeFile(path.join(cwd, '.cursor', 'rules', 'engram.mdc'), '---\ndescription: Engram\n---\n\n<!-- engram:start -->\nOLD\n<!-- engram:end -->\n');
  await writeFile(path.join(cwd, '.cursor', 'mcp.json'), '{ invalid json\n');
  return { cwd, env: globalEnv };
}

async function replaceableBlockers(cwd, plan) {
  const rows = [];
  for (const item of plan.items.filter((row) => row.status === 'conflict' || row.status === 'invalid')) {
    const review = await apiUpgradeReview(cwd, plan.fingerprint, item.id);
    if (review.proposal.replaceable) rows.push(item);
  }
  return rows;
}

test('web upgrade batch review never force-confirms ownership-gated conflicts', async () => {
  const { cwd, env } = await batchUpgradeFixture('engram-web-upgrade-batch-force-');
  const old = {
    config: process.env.ENGRAM_CONFIG_DIR,
    global: process.env.ENGRAM_GLOBAL_DIR,
    agentHome: process.env.ENGRAM_AGENT_HOME,
    agentConfigHome: process.env.ENGRAM_AGENT_CONFIG_HOME
  };
  process.env.ENGRAM_CONFIG_DIR = env.ENGRAM_CONFIG_DIR;
  process.env.ENGRAM_GLOBAL_DIR = env.ENGRAM_GLOBAL_DIR;
  process.env.ENGRAM_AGENT_HOME = env.ENGRAM_AGENT_HOME;
  process.env.ENGRAM_AGENT_CONFIG_HOME = env.ENGRAM_AGENT_CONFIG_HOME;
  try {
    const plan = await apiUpgradePlan(cwd);
    const forceable = plan.items.find((item) => item.kind === 'skillset' && item.status === 'conflict' && item.forceMode === 'replace-file');
    assert.ok(forceable, JSON.stringify(plan.items, null, 2));
    await assert.rejects(apiUpgradeResolveBatch(cwd, { fingerprint: plan.fingerprint, itemIds: [forceable.id] }), /individually/i);
    const refreshed = await apiUpgradePlan(cwd);
    assert.equal(refreshed.review?.items.find((row) => row.itemId === forceable.id)?.state, 'pending');
  } finally {
    restoreEnv('ENGRAM_CONFIG_DIR', old.config);
    restoreEnv('ENGRAM_GLOBAL_DIR', old.global);
    restoreEnv('ENGRAM_AGENT_HOME', old.agentHome);
    restoreEnv('ENGRAM_AGENT_CONFIG_HOME', old.agentConfigHome);
    await rm(cwd, { recursive: true, force: true });
  }
});

test('web upgrade batch review rejects a non-forceable manual selection without partial writes', async () => {
  const { cwd, env } = await batchUpgradeFixture('engram-web-upgrade-batch-nonreplaceable-');
  const old = {
    config: process.env.ENGRAM_CONFIG_DIR,
    global: process.env.ENGRAM_GLOBAL_DIR,
    agentHome: process.env.ENGRAM_AGENT_HOME,
    agentConfigHome: process.env.ENGRAM_AGENT_CONFIG_HOME
  };
  process.env.ENGRAM_CONFIG_DIR = env.ENGRAM_CONFIG_DIR;
  process.env.ENGRAM_GLOBAL_DIR = env.ENGRAM_GLOBAL_DIR;
  process.env.ENGRAM_AGENT_HOME = env.ENGRAM_AGENT_HOME;
  process.env.ENGRAM_AGENT_CONFIG_HOME = env.ENGRAM_AGENT_CONFIG_HOME;
  try {
    const plan = await apiUpgradePlan(cwd);
    const manual = plan.items.find((item) => item.kind === 'memory' && item.status === 'invalid');
    assert.ok(manual, JSON.stringify(plan.items, null, 2));
    await assert.rejects(apiUpgradeResolveBatch(cwd, { fingerprint: plan.fingerprint, itemIds: [manual.id] }), /individually/i);
    const refreshed = await apiUpgradePlan(cwd);
    assert.equal(refreshed.review?.items.find((row) => row.itemId === manual.id)?.state, 'pending');
  } finally {
    restoreEnv('ENGRAM_CONFIG_DIR', old.config);
    restoreEnv('ENGRAM_GLOBAL_DIR', old.global);
    restoreEnv('ENGRAM_AGENT_HOME', old.agentHome);
    restoreEnv('ENGRAM_AGENT_CONFIG_HOME', old.agentConfigHome);
    await rm(cwd, { recursive: true, force: true });
  }
});

test('web upgrade batch review rejects empty unknown already-reviewed and stale forceable selections', async () => {
  const { cwd, env } = await batchUpgradeFixture('engram-web-upgrade-batch-guards-');
  const old = {
    config: process.env.ENGRAM_CONFIG_DIR,
    global: process.env.ENGRAM_GLOBAL_DIR,
    agentHome: process.env.ENGRAM_AGENT_HOME,
    agentConfigHome: process.env.ENGRAM_AGENT_CONFIG_HOME
  };
  process.env.ENGRAM_CONFIG_DIR = env.ENGRAM_CONFIG_DIR;
  process.env.ENGRAM_GLOBAL_DIR = env.ENGRAM_GLOBAL_DIR;
  process.env.ENGRAM_AGENT_HOME = env.ENGRAM_AGENT_HOME;
  process.env.ENGRAM_AGENT_CONFIG_HOME = env.ENGRAM_AGENT_CONFIG_HOME;
  try {
    let plan = await apiUpgradePlan(cwd);
    let forceable = plan.items.find((item) => item.kind === 'skillset' && item.status === 'conflict' && item.forceMode === 'replace-file');
    assert.ok(forceable, JSON.stringify(plan.items, null, 2));
    await assert.rejects(apiUpgradeResolveBatch(cwd, { fingerprint: plan.fingerprint, itemIds: [] }), /select at least one/i);
    await assert.rejects(apiUpgradeResolveBatch(cwd, { fingerprint: plan.fingerprint, itemIds: ['missing'] }), /no longer exists/i);
    await apiUpgradeResolve(cwd, { fingerprint: plan.fingerprint, itemId: forceable.id, state: 'force-latest' });
    await assert.rejects(apiUpgradeResolveBatch(cwd, { fingerprint: plan.fingerprint, itemIds: [forceable.id] }), /already reviewed/i);

    await writeFile(forceable.file, '# Changed after review\n');
    plan = await apiUpgradePlan(cwd);
    forceable = plan.items.find((item) => item.kind === 'skillset' && item.status === 'conflict' && item.file.endsWith(path.join('.agents', 'engram.md')));
    assert.ok(forceable);
    const staleState = plan.review?.items.find((row) => row.itemId === forceable.id);
    assert.equal(staleState?.state, 'pending');
    assert.equal(staleState?.stale, true);
    await assert.rejects(apiUpgradeResolveBatch(cwd, { fingerprint: plan.fingerprint, itemIds: [forceable.id] }), /stale conflict individually/i);
  } finally {
    restoreEnv('ENGRAM_CONFIG_DIR', old.config);
    restoreEnv('ENGRAM_GLOBAL_DIR', old.global);
    restoreEnv('ENGRAM_AGENT_HOME', old.agentHome);
    restoreEnv('ENGRAM_AGENT_CONFIG_HOME', old.agentConfigHome);
    await rm(cwd, { recursive: true, force: true });
  }
});


test('web upgrade open-file resolves only the server-side plan item and rejects stale requests', async () => {
  const { cwd, env } = await tempWorkspace('engram-web-open-upgrade-file-');
  const old = { config: process.env.ENGRAM_CONFIG_DIR, global: process.env.ENGRAM_GLOBAL_DIR };
  process.env.ENGRAM_CONFIG_DIR = env.ENGRAM_CONFIG_DIR;
  process.env.ENGRAM_GLOBAL_DIR = env.ENGRAM_GLOBAL_DIR;
  try {
    await mkdir(path.join(cwd, '.agents'), { recursive: true });
    await writeFile(path.join(cwd, 'AGENTS.md'), '# Human\n\n<!-- engram:start -->\nOLD\n<!-- engram:end -->\n');
    const guideFile = path.join(cwd, '.agents', 'engram.md');
    await writeFile(guideFile, '# Human-owned custom guide\n');
    const plan = await apiUpgradePlan(cwd);
    const item = plan.items.find((row) => row.status === 'conflict' && path.resolve(row.file) === path.resolve(guideFile));
    assert.ok(item, JSON.stringify(plan.items, null, 2));
    let launchedFile = '';
    const deps = {
      resolveEditor: () => ['fake-editor'],
      launch: async (_command, file) => { launchedFile = file; }
    };
    const result = await apiUpgradeOpenFile(cwd, { fingerprint: plan.fingerprint, itemId: item.id, path: '/etc/passwd' }, deps);
    assert.equal(path.resolve(result.file), path.resolve(guideFile));
    assert.equal(path.resolve(launchedFile), path.resolve(guideFile));
    await assert.rejects(apiUpgradeOpenFile(cwd, { fingerprint: 'stale', itemId: item.id }, deps), /stale/i);
    await assert.rejects(apiUpgradeOpenFile(cwd, { fingerprint: plan.fingerprint, itemId: 'missing' }, deps), /not found/i);
    await writeFile(guideFile, '# externally changed\n');
    await assert.rejects(apiUpgradeOpenFile(cwd, { fingerprint: plan.fingerprint, itemId: item.id }, deps), /stale/i);
  } finally {
    restoreEnv('ENGRAM_CONFIG_DIR', old.config);
    restoreEnv('ENGRAM_GLOBAL_DIR', old.global);
    await rm(cwd, { recursive: true, force: true });
  }
});
