/** Admin and roadmap commands: ignore, roles, conflicts, hooks, skillsets, upgrade. */
import { execFile } from 'node:child_process';
import fs from 'node:fs/promises';
import path from 'node:path';
import { getContext } from '../core/memory/context.js';
import { initWorkspace } from '../core/memory/storage.js';
import { loadConfig, scopeRootsForConfig, workspaceRoot, writeConfig } from '../core/runtime/config.js';
import { HELP_FILE, VERSION } from '../core/runtime/constants.js';
import { isIgnored } from '../core/safety/ignore.js';
import { ensureDir, exists, readText, writeText } from '../core/system/fsx.js';
import { findConflicts, resolveConflicts } from '../core/vcs/conflict.js';
import {
  globalSkillsetRegistryPath,
  installGlobalSkillset,
  installSkillset,
  readGlobalSkillsetRegistry,
  refreshGlobalSkillsets,
  skillsetTargets,
  type InstallResult
} from '../core/integrations/skillset.js';
import { git } from '../core/vcs/git.js';
import { formatRecords, type RecordBlock } from '../core/cli/format.js';
import { renderHelp } from '../core/cli/help.js';
import type { RuleVariant } from '../core/runtime/types.js';

/** Inspect or update ignore patterns. */
export async function cmdIgnore(args: string[]): Promise<string> {
  const ctx = await getContext();
  const [sub, value] = args;
  if (sub === 'check') return isIgnored(value ?? '', ctx.ignorePatterns) ? 'ignored' : 'visible';
  if (sub === 'add' && value) {
    const file = path.join(process.cwd(), '.engramignore');
    await writeText(file, `${(await readText(file)).trimEnd()}\n${value}\n`);
    return `Added ignore pattern: ${value}`;
  }
  return formatRecords('Ignore status', [{
    title: ctx.config.ignore.source,
    fields: [['Also ignore', ctx.config.ignore.also_ignore.join(', ') || '(none)'], ['Hidden', ctx.hiddenCount]]
  }]);
}

/** Persist local developer roles in config. */
export async function cmdSetRole(args: string[]): Promise<string> {
  const ctx = await getContext();
  ctx.config.roles = args;
  await writeConfig(process.cwd(), ctx.config);
  return `Roles: ${args.join(', ') || '(none)'}`;
}

/** Enable, disable, or inspect rule variant rendering. */
export async function cmdSetRuleVariant(args: string[]): Promise<string> {
  const ctx = await getContext();
  const value = (args[0] ?? 'status').toLowerCase();
  if (value === 'status') return ruleVariantStatus(ctx.config.rule_variants);
  if (['off', 'disable', 'disabled'].includes(value)) {
    ctx.config.rule_variants = { enabled: false, active: 'balanced' };
  } else if (isRuleVariant(value)) {
    ctx.config.rule_variants = { enabled: true, active: value };
  } else {
    throw new Error('set-rule-variant expects off, light, balanced, strict, or status');
  }
  await writeConfig(process.cwd(), ctx.config);
  return ruleVariantStatus(ctx.config.rule_variants);
}

/** Resolve or preview workspace memory merge conflicts. */
export async function cmdResolveConflicts(flags: Record<string, any> = {}): Promise<string> {
  if (flags.auto) throw new Error('resolve-conflicts --auto is not supported; use --dry-run or resolve-conflicts');
  const conflicts = await findConflicts(process.cwd());
  if (!conflicts.length) return 'No workspace Engram merge conflicts found';
  if (flags['dry-run']) return formatRecords('Conflict dry-run', conflicts.map((conflict) => ({
    title: `DRY-RUN ${conflict.kind} ${conflict.file}`,
    fields: [['Summary', conflict.summary]]
  })));
  const results = await resolveConflicts(process.cwd(), false);
  return formatRecords('Resolved conflicts', results.map((conflict) => ({
    title: `RESOLVED ${conflict.kind} ${conflict.file}`,
    fields: [['Decision', conflict.decision], ['Stage', conflict.staged ? 'staged' : 'stage skipped']]
  })));
}

/** Install opt-in Git hooks that call Engram commands. */
export async function cmdInstallHooks(): Promise<string> {
  const hookDir = await gitHookDir(process.cwd());
  await ensureDir(hookDir);
  const results = [];
  results.push(await writeGeneratedHook(path.join(hookDir, 'post-merge'), '#!/bin/sh\nnpx @the-long-ride/engram resolve-conflicts\n'));
  results.push(await writeGeneratedHook(path.join(hookDir, 'pre-commit'), '#!/bin/sh\nnpx @the-long-ride/engram verify workspace\n'));
  return formatRecords('Engram Git hooks', results.map((result) => ({ title: result })));
}

async function writeGeneratedHook(file: string, body: string): Promise<string> {
  const existing = await readText(file);
  if (existing && !existing.includes('Generated by Engram')) return `SKIPPED ${path.basename(file)}: human-authored file exists`;
  const script = body.startsWith('#!')
    ? body.replace(/\r?\n/, '\n# Generated by Engram. Edit with care.\n')
    : `# Generated by Engram. Edit with care.\n${body}`;
  await writeText(file, script);
  await fs.chmod(file, 0o755).catch(() => undefined);
  return `WRITTEN ${path.basename(file)}`;
}

async function gitHookDir(cwd: string): Promise<string> {
  try {
    const hookDir = (await git(['-C', cwd, 'rev-parse', '--git-path', 'hooks'])).trim();
    return path.isAbsolute(hookDir) ? hookDir : path.join(cwd, hookDir);
  } catch {
    throw new Error('install-hooks requires a Git repository');
  }
}

/** Install agent-host instruction files for Engram skillset integration. */
export async function cmdInstallSkillset(args: string[], flags: Record<string, any> = {}): Promise<string> {
  if (args[0] === 'list') return skillsetTargets().join('\n');
  const target = args[0] ?? 'all';
  const global = flags.global === true;
  const results = global
    ? await installGlobalSkillset(target, { force: Boolean(flags.force) })
    : await installSkillset(process.cwd(), target, Boolean(flags.force));
  const records = installResultRecords(results);
  return [
    formatRecords(global ? 'Global skillset install' : 'Skillset install', records),
    ...skillsetInstallHints(results, global)
  ].join('\n');
}

/** Upgrade Engram package guidance, global memory scaffold, and registered global skillsets. */
export async function cmdUpgrade(args: string[] = [], flags: Record<string, any> = {}): Promise<string> {
  if (flags['memory-only'] === true && flags['global-skillsets-only'] === true) throw new Error('upgrade cannot use --memory-only and --global-skillsets-only together');
  const plan = flags.plan === true || flags['dry-run'] === true;
  const records: RecordBlock[] = [];
  records.push(await upgradePackageRecord(flags, plan));
  if (flags['global-skillsets-only'] !== true) {
    records.push(await workspaceHelpUpgradeRecord(plan));
    records.push(...await globalMemoryUpgradeRecords(plan, Boolean(flags.force)));
  }
  if (flags['memory-only'] !== true) records.push(...await globalSkillsetUpgradeRecords(args, flags, plan));
  return [
    formatRecords(plan ? 'Upgrade plan' : 'Upgrade', records),
    '',
    'Quick update:',
    '  npm install -g @the-long-ride/engram@latest',
    '  engram upgrade'
  ].join('\n');
}

async function workspaceHelpUpgradeRecord(plan: boolean): Promise<RecordBlock> {
  const root = workspaceRoot(process.cwd());
  const file = path.join(root, HELP_FILE);
  if (!(await exists(root))) {
    return { title: 'SKIPPED workspace help', fields: [['Reason', 'workspace memory is not initialized; run engram init']] };
  }
  if (plan) return { title: 'PLAN workspace help', fields: [['Path', file], ['Action', 'refresh generated HELP.md']] };
  await writeText(file, renderHelp());
  return { title: 'UPDATED workspace help', fields: [['Path', file]] };
}

function installResultRecords(results: InstallResult[]): RecordBlock[] {
  return results.map((result) => ({
    title: `${result.action.toUpperCase()} ${result.target}: ${result.file}`,
    fields: [
      ...(result.mode ? [['Mode', result.mode] as [string, string]] : []),
      ...(result.reason ? [['Reason', result.reason] as [string, string]] : [])
    ]
  }));
}

function skillsetInstallHints(results: InstallResult[], global = false): string[] {
  const hints = [];
  if (global) hints.push(`Registry: ${globalSkillsetRegistryPath()}`);
  if (results.some((result) => result.action === 'skipped')) hints.push('Skipped targets can be installed manually when the agent exposes a stable user/global rule path.');
  if (!results.some((result) => result.target === 'slash')) return hints;
  hints.push(
    'Hint: if /engram is not visible in an already-open chat, restart or reload the agent chat after the new slash files are written.',
    global ? 'Global Claude paths: ~/.claude/commands/engram.md and ~/.claude/skills/engram/SKILL.md' : 'Claude paths: .claude/commands/engram.md and .claude/skills/engram/SKILL.md'
  );
  return hints;
}

async function upgradePackageRecord(flags: Record<string, any>, plan: boolean): Promise<RecordBlock> {
  const latest = await latestVersion(flags);
  if (flags.self === true && !plan) {
    const result = await runNpm(['install', '-g', '@the-long-ride/engram@latest'], 120000).catch((error) => `failed: ${error.message}`);
    return { title: 'PACKAGE self update', fields: [['Current', VERSION], ['Latest', latest], ['Result', compact(result)]] };
  }
  return {
    title: flags.self === true ? 'PLAN package self update' : 'PACKAGE recommendation',
    fields: [
      ['Current', VERSION],
      ['Latest', latest],
      ['Command', 'npm install -g @the-long-ride/engram@latest']
    ]
  };
}

async function globalMemoryUpgradeRecords(plan: boolean, force: boolean): Promise<RecordBlock[]> {
  const config = await loadConfig(process.cwd());
  const roots = scopeRootsForConfig(process.cwd(), config);
  if (!roots.global) return [{ title: 'SKIPPED global memory', fields: [['Reason', 'global memory is not configured; run engram init --global-only --global-path <path>']] }];
  if (plan) return [{ title: 'PLAN global memory', fields: [['Path', roots.global], ['Action', 'reconcile global-only scaffold']] }];
  const lines = await initWorkspace(process.cwd(), force, config.global_git.branch, roots.global, { globalOnly: true });
  return [{ title: 'UPDATED global memory', fields: [['Path', roots.global]], lines }];
}

async function globalSkillsetUpgradeRecords(args: string[], flags: Record<string, any>, plan: boolean): Promise<RecordBlock[]> {
  const target = typeof flags.target === 'string' ? flags.target : args[0] ?? '';
  const registry = await readGlobalSkillsetRegistry();
  if (!target && !Object.keys(registry.installs).length) {
    return [{
      title: 'SKIPPED global skillsets',
      fields: [
        ['Reason', 'no registered global skillsets yet'],
        ['Start with', 'engram install-skillset --global codex']
      ]
    }];
  }
  const results = target
    ? await installGlobalSkillset(target, { force: Boolean(flags.force), plan })
    : await refreshGlobalSkillsets('', { force: Boolean(flags.force), plan });
  return installResultRecords(results);
}

async function latestVersion(flags: Record<string, any>): Promise<string> {
  if (flags['no-version-check'] === true) return 'not checked';
  if (process.env.ENGRAM_LATEST_VERSION?.trim()) return process.env.ENGRAM_LATEST_VERSION.trim();
  if (flags.latest !== true && flags.self !== true) return 'not checked (use --latest to query npm)';
  return compact(await runNpm(['view', '@the-long-ride/engram', 'version', '--silent'], 5000).catch((error) => `unavailable: ${error.message}`));
}

function runNpm(args: string[], timeout: number): Promise<string> {
  const command = process.platform === 'win32' ? 'npm.cmd' : 'npm';
  return new Promise((resolve, reject) => {
    execFile(command, args, { encoding: 'utf8', timeout }, (error: any, stdout: string, stderr: string) => {
      if (error) reject(new Error(compact(stderr || error.message)));
      else resolve(stdout.trim());
    });
  });
}

function compact(value: string): string {
  return value.trim().replace(/\s+/g, ' ') || '-';
}

function isRuleVariant(value: string): value is RuleVariant {
  return ['light', 'balanced', 'strict'].includes(value);
}

function ruleVariantStatus(config: { enabled: boolean; active: RuleVariant }): string {
  return `Rule variants: ${config.enabled ? config.active : 'off (balanced default)'}`;
}
