allowBuilds:
  '@swc/core': true
  core-js: true
  esbuild: true
overrides:
  serialize-javascript: ^7.0.5
  uuid: ^11.1.1
packages:
  - '.'

onlyBuiltDependencies:
  - '@swc/core'
  - core-js
  - esbuild
